"""empty message

Revision ID: 0163e3728b2e
Revises: f8daa9bea417
Create Date: 2025-06-17 23:24:24.822850

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0163e3728b2e'
down_revision = 'f8daa9bea417'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('anime_subscriptions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('time_subscribed', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('anime_subscriptions', schema=None) as batch_op:
        batch_op.drop_column('time_subscribed')

    # ### end Alembic commands ###
