"""empty message

Revision ID: 0761bbc2570c
Revises: ce8715711132
Create Date: 2025-03-02 20:40:09.097259

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0761bbc2570c'
down_revision = 'ce8715711132'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('forum_subscribers')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('forum_subscribers',
    sa.Column('user_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('forum_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['forum_id'], ['posts.id'], name='forum_subscribers_forum_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='forum_subscribers_user_id_fkey'),
    sa.PrimaryKeyConstraint('user_id', 'forum_id', name='pk_forum_subscribers')
    )
    # ### end Alembic commands ###
