"""empty message

Revision ID: 08c9d52d735f
Revises: f505901ccc85
Create Date: 2025-04-02 22:27:21.302400

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '08c9d52d735f'
down_revision = 'f505901ccc85'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('forums', schema=None) as batch_op:
        batch_op.drop_column('pfp')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('forums', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pfp', sa.VARCHAR(length=128), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
