"""empty message

Revision ID: 11ef89692498
Revises: e57ea454d9c6
Create Date: 2025-02-26 20:16:10.333892

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '11ef89692498'
down_revision = 'e57ea454d9c6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_tickets',
    sa.Column('user_id', sa.BIGINT(), nullable=False),
    sa.Column('time_raised', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('description', sa.VARCHAR(length=512), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('deleted', sa.BOOLEAN(), server_default=sa.text('false'), nullable=False))
        batch_op.add_column(sa.Column('time_deleted', postgresql.TIMESTAMP(), nullable=True))
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(length=64),
               type_=sa.VARCHAR(length=320),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(length=320),
               type_=sa.VARCHAR(length=64),
               existing_nullable=False)
        batch_op.drop_column('time_deleted')
        batch_op.drop_column('deleted')

    op.drop_table('user_tickets')
    # ### end Alembic commands ###
