"""empty message

Revision ID: 138fdcef8a1b
Revises: c48534fd5f89
Create Date: 2025-06-08 16:33:30.648546

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '138fdcef8a1b'
down_revision = 'c48534fd5f89'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.alter_column('reports',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_column('score')

    with op.batch_alter_table('forums', schema=None) as batch_op:
        batch_op.alter_column('admin_count',
               existing_type=sa.SMALLINT(),
               nullable=False)

    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.alter_column('score',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('total_comments',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('saves',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('reports',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.alter_column('reports',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('saves',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('total_comments',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('score',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('forums', schema=None) as batch_op:
        batch_op.alter_column('admin_count',
               existing_type=sa.SMALLINT(),
               nullable=True)

    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('score', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.alter_column('reports',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
