"""empty message

Revision ID: 258bd70f9d5c
Revises: a25f7819cca0
Create Date: 2025-06-03 14:41:05.964306

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '258bd70f9d5c'
down_revision = 'a25f7819cca0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rtbf', sa.BOOLEAN(), server_default=sa.text('false'), nullable=False))
        batch_op.drop_column('rtfb')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rtfb', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False))
        batch_op.drop_column('rtbf')

    # ### end Alembic commands ###
