"""empty message

Revision ID: 25af3634aada
Revises: 138fdcef8a1b
Create Date: 2025-06-10 18:23:13.847570

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '25af3634aada'
down_revision = '138fdcef8a1b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rtbf_hidden', sa.BOOLEAN(), nullable=True))

    with op.batch_alter_table('forums', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rtbf_hidden', sa.BOOLEAN(), nullable=True))

    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rtbf_hidden', sa.BOOLEAN(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.drop_column('rtbf_hidden')

    with op.batch_alter_table('forums', schema=None) as batch_op:
        batch_op.drop_column('rtbf_hidden')

    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.drop_column('rtbf_hidden')

    # ### end Alembic commands ###
