"""empty message

Revision ID: 2e6d0b6ed80f
Revises: e6efe425fec5
Create Date: 2025-02-27 22:02:08.452279

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '2e6d0b6ed80f'
down_revision = 'e6efe425fec5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('forum_admins',
    sa.Column('forum_id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.BIGINT(), nullable=False),
    # sa.Column('role', postgresql.ENUM('admin', 'super', 'owner', name='ADMIN_ROLES'), server_default=sa.text("'admin'"), nullable=False),     ### Past upgrade already created this enum ###
    sa.ForeignKeyConstraint(['forum_id'], ['forums.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('forum_id', 'user_id', name='pk_forum_admins')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('forum_admins')
    # ### end Alembic commands ###
