"""empty message

Revision ID: 49b851131dd0
Revises: 2726869d5e19
Create Date: 2025-03-30 11:34:32.047680

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '49b851131dd0'
down_revision = '2726869d5e19'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('deleted', sa.BOOLEAN(), server_default=sa.text('false'), nullable=False))
        batch_op.add_column(sa.Column('time_deleted', postgresql.TIMESTAMP(), nullable=True))

    with op.batch_alter_table('forum_rules', schema=None) as batch_op:
        batch_op.add_column(sa.Column('deleted', sa.BOOLEAN(), server_default=sa.text('false'), nullable=False))
        batch_op.add_column(sa.Column('time_deleted', postgresql.TIMESTAMP(), nullable=True))

    with op.batch_alter_table('forums', schema=None) as batch_op:
        batch_op.add_column(sa.Column('deleted', sa.BOOLEAN(), server_default=sa.text('false'), nullable=False))
        batch_op.add_column(sa.Column('time_deleted', postgresql.TIMESTAMP(), nullable=True))

    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('deleted', sa.BOOLEAN(), server_default=sa.text('false'), nullable=False))
        batch_op.add_column(sa.Column('time_deleted', postgresql.TIMESTAMP(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.drop_column('time_deleted')
        batch_op.drop_column('deleted')

    with op.batch_alter_table('forums', schema=None) as batch_op:
        batch_op.drop_column('time_deleted')
        batch_op.drop_column('deleted')

    with op.batch_alter_table('forum_rules', schema=None) as batch_op:
        batch_op.drop_column('time_deleted')
        batch_op.drop_column('deleted')

    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.drop_column('time_deleted')
        batch_op.drop_column('deleted')

    # ### end Alembic commands ###
