"""empty message

Revision ID: 5c241b905069
Revises: 08c9d52d735f
Create Date: 2025-04-06 09:13:56.944326

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5c241b905069'
down_revision = '08c9d52d735f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('forums', schema=None) as batch_op:
        batch_op.drop_column('color_theme')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('forums', schema=None) as batch_op:
        batch_op.add_column(sa.Column('color_theme', sa.SMALLINT(), server_default=sa.text("'1'::smallint"), autoincrement=False, nullable=False))

    # ### end Alembic commands ###
