"""empty message

Revision ID: 84f2c6a769b8
Revises: 11ef89692498
Create Date: 2025-02-27 15:14:21.094249

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '84f2c6a769b8'
down_revision = '11ef89692498'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('password_recovery_tokens',
    sa.Column('user_id', sa.BIGINT(), nullable=False),
    sa.Column('expiry', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('url_hash', postgresql.BYTEA(length=512), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id')
    )
    with op.batch_alter_table('password_recovery_tokens', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_password_recovery_tokens_expiry'), ['expiry'], unique=False)
        batch_op.create_index(batch_op.f('ix_password_recovery_tokens_url_hash'), ['url_hash'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('password_recovery_tokens', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_password_recovery_tokens_url_hash'))
        batch_op.drop_index(batch_op.f('ix_password_recovery_tokens_expiry'))

    op.drop_table('password_recovery_tokens')
    # ### end Alembic commands ###
