"""empty message

Revision ID: 98a994a5980f
Revises: 258bd70f9d5c
Create Date: 2025-06-08 14:27:05.270267

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '98a994a5980f'
down_revision = '258bd70f9d5c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('post_reports')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('post_reports',
    sa.Column('user_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('post_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('report_time', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('report_description', sa.VARCHAR(length=256), autoincrement=False, nullable=False),
    sa.Column('report_tag', postgresql.ENUM('spam', 'harassment', 'hate', 'violence', 'other', name='REPORT_TAGS'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], name='post_reports_post_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='post_reports_user_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'post_id', name='pk_post_reports')
    )
    # ### end Alembic commands ###
