"""empty message

Revision ID: a1d8f5a0c609
Revises: caf1d675b13a
Create Date: 2025-04-10 00:11:12.068509

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a1d8f5a0c609'
down_revision = 'caf1d675b13a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('animes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('banner', sa.VARCHAR(length=128), nullable=True))

    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.drop_constraint('comments_parent_post_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'posts', ['parent_post'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'forums', ['parent_forum'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('forum_rules', schema=None) as batch_op:
        batch_op.drop_constraint('forum_rules_forum_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'forums', ['forum_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.drop_constraint('posts_forum_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'forums', ['forum_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('posts_forum_id_fkey', 'forums', ['forum_id'], ['id'])

    with op.batch_alter_table('forum_rules', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('forum_rules_forum_id_fkey', 'forums', ['forum_id'], ['id'])

    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('comments_parent_post_fkey', 'posts', ['parent_post'], ['id'])

    with op.batch_alter_table('animes', schema=None) as batch_op:
        batch_op.drop_column('banner')

    # ### end Alembic commands ###
