"""empty message

Revision ID: a25f7819cca0
Revises: 8730ffc1296a
Create Date: 2025-06-02 14:23:53.940321

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a25f7819cca0'
down_revision = '8730ffc1296a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('comment_reports')
    op.drop_table('comment_votes')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('comment_votes',
    sa.Column('voter_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('comment_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('vote', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['comment_id'], ['comments.id'], name='comment_votes_comment_id_fkey'),
    sa.ForeignKeyConstraint(['voter_id'], ['users.id'], name='comment_votes_voter_id_fkey'),
    sa.PrimaryKeyConstraint('voter_id', 'comment_id', name='pk_comment_votes')
    )
    op.create_table('comment_reports',
    sa.Column('user_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('comment_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['comment_id'], ['comments.id'], name='comment_reports_comment_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='comment_reports_user_id_fkey'),
    sa.PrimaryKeyConstraint('user_id', 'comment_id', name='pk_comment_reports')
    )
    # ### end Alembic commands ###
