"""empty message

Revision ID: b0f3cbfa47e0
Revises: 2e6d0b6ed80f
Create Date: 2025-02-27 22:08:19.209554

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'b0f3cbfa47e0'
down_revision = '2e6d0b6ed80f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('forum_admins', schema=None) as batch_op:
        batch_op.add_column(sa.Column('role', postgresql.ENUM('admin', 'super', 'owner', name='ADMIN_ROLES'), server_default=sa.text("'admin'"), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('forum_admins', schema=None) as batch_op:
        batch_op.drop_column('role')

    # ### end Alembic commands ###
