"""empty message

Revision ID: c48534fd5f89
Revises: 98a994a5980f
Create Date: 2025-06-08 14:27:44.125153

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'c48534fd5f89'
down_revision = '98a994a5980f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('post_reports',
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('post_id', sa.BigInteger(), nullable=False),
    sa.Column('report_tag', postgresql.ENUM('spam', 'harassment', 'hate', 'violence', 'other', name='REPORT_TAGS', create_type=False), nullable=False),
    sa.Column('report_time', postgresql.TIMESTAMP(), nullable=True),
    sa.Column('report_description', sa.VARCHAR(length=256), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'post_id', 'report_tag')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('post_reports')
    # ### end Alembic commands ###
