"""empty message

Revision ID: c96cd81adbbf
Revises: 25af3634aada
Create Date: 2025-06-12 13:29:16.255801

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'c96cd81adbbf'
down_revision = '25af3634aada'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('comment_reports',
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('comment_id', sa.BigInteger(), nullable=False),
    sa.Column('report_tag', postgresql.ENUM('spam', 'harassment', 'hate', 'violence', 'other', name='REPORT_TAGS', create_type=False), nullable=False),
    sa.Column('report_time', postgresql.TIMESTAMP(), nullable=True),
    sa.Column('report_description', sa.VARCHAR(length=256), nullable=False),
    sa.ForeignKeyConstraint(['comment_id'], ['comments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'comment_id', 'report_tag')
    )
    op.create_table('comment_votes',
    sa.Column('voter_id', sa.BigInteger(), nullable=False),
    sa.Column('comment_id', sa.BigInteger(), nullable=False),
    sa.Column('vote', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['comment_id'], ['comments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['voter_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('voter_id', 'comment_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('comment_votes')
    op.drop_table('comment_reports')
    # ### end Alembic commands ###
