"""empty message

Revision ID: caf1d675b13a
Revises: 5c241b905069
Create Date: 2025-04-07 12:13:07.181616

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'caf1d675b13a'
down_revision = '5c241b905069'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('anime_genres', schema=None) as batch_op:
        batch_op.drop_constraint('anime_genres_anime_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('anime_genres_genre_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'genres', ['genre_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'animes', ['anime_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('anime_subscriptions', schema=None) as batch_op:
        batch_op.drop_constraint('anime_subscriptions_user_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('anime_subscriptions_anime_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'animes', ['anime_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('comment_reports', schema=None) as batch_op:
        batch_op.drop_constraint('comment_reports_comment_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'comments', ['comment_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('forum_admins', schema=None) as batch_op:
        batch_op.drop_constraint('forum_admins_forum_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('forum_admins_user_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'forums', ['forum_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('forum_flairs', schema=None) as batch_op:
        batch_op.drop_constraint('forum_flairs_forum_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'forums', ['forum_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('forum_subscriptions', schema=None) as batch_op:
        batch_op.drop_constraint('forum_subscriptions_user_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('forum_subscriptions_forum_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'forums', ['forum_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('post_reports', schema=None) as batch_op:
        batch_op.drop_constraint('post_reports_post_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('post_reports_user_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'posts', ['post_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('post_saves', schema=None) as batch_op:
        batch_op.drop_constraint('post_saves_post_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('post_saves_user_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'posts', ['post_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('post_votes', schema=None) as batch_op:
        batch_op.drop_constraint('post_votes_post_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'posts', ['post_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('stream_links', schema=None) as batch_op:
        batch_op.drop_constraint('stream_links_anime_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'animes', ['anime_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stream_links', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('stream_links_anime_id_fkey', 'animes', ['anime_id'], ['id'])

    with op.batch_alter_table('post_votes', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('post_votes_post_id_fkey', 'posts', ['post_id'], ['id'])

    with op.batch_alter_table('post_saves', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('post_saves_user_id_fkey', 'users', ['user_id'], ['id'])
        batch_op.create_foreign_key('post_saves_post_id_fkey', 'posts', ['post_id'], ['id'])

    with op.batch_alter_table('post_reports', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('post_reports_user_id_fkey', 'users', ['user_id'], ['id'])
        batch_op.create_foreign_key('post_reports_post_id_fkey', 'posts', ['post_id'], ['id'])

    with op.batch_alter_table('forum_subscriptions', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('forum_subscriptions_forum_id_fkey', 'forums', ['forum_id'], ['id'])
        batch_op.create_foreign_key('forum_subscriptions_user_id_fkey', 'users', ['user_id'], ['id'])

    with op.batch_alter_table('forum_flairs', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('forum_flairs_forum_id_fkey', 'forums', ['forum_id'], ['id'])

    with op.batch_alter_table('forum_admins', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('forum_admins_user_id_fkey', 'users', ['user_id'], ['id'])
        batch_op.create_foreign_key('forum_admins_forum_id_fkey', 'forums', ['forum_id'], ['id'])

    with op.batch_alter_table('comment_reports', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('comment_reports_comment_id_fkey', 'comments', ['comment_id'], ['id'])

    with op.batch_alter_table('anime_subscriptions', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('anime_subscriptions_anime_id_fkey', 'animes', ['anime_id'], ['id'])
        batch_op.create_foreign_key('anime_subscriptions_user_id_fkey', 'users', ['user_id'], ['id'])

    with op.batch_alter_table('anime_genres', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('anime_genres_genre_id_fkey', 'genres', ['genre_id'], ['id'])
        batch_op.create_foreign_key('anime_genres_anime_id_fkey', 'animes', ['anime_id'], ['id'])

    # ### end Alembic commands ###
