"""empty message

Revision ID: d5833f423191
Revises: dddc44d42f79
Create Date: 2025-06-01 10:33:43.379797

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd5833f423191'
down_revision = 'dddc44d42f79'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('forum_flairs')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('_alias')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('_alias', sa.VARCHAR(length=64), autoincrement=False, nullable=True))

    op.create_table('forum_flairs',
    sa.Column('forum_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('flair_name', sa.VARCHAR(length=32), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['forum_id'], ['forums.id'], name='forum_flairs_forum_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('forum_id', 'flair_name', name='pk_forum_flairs')
    )
    # ### end Alembic commands ###
