"""empty message

Revision ID: dddc44d42f79
Revises: fc411ecd643e
Create Date: 2025-05-29 19:01:34.638695

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dddc44d42f79'
down_revision = 'fc411ecd643e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.drop_constraint('comments_parent_thread_fkey', type_='foreignkey')
        batch_op.drop_constraint('comments_replying_to_fkey', type_='foreignkey')
        batch_op.drop_column('parent_thread')
        batch_op.drop_column('replying_to')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('replying_to', sa.BIGINT(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('parent_thread', sa.BIGINT(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('comments_replying_to_fkey', 'comments', ['replying_to'], ['id'])
        batch_op.create_foreign_key('comments_parent_thread_fkey', 'comments', ['parent_thread'], ['id'])

    # ### end Alembic commands ###
