"""empty message

Revision ID: e6efe425fec5
Revises: 84f2c6a769b8
Create Date: 2025-02-27 20:13:04.120421

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e6efe425fec5'
down_revision = '84f2c6a769b8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('animes',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('title', sa.VARCHAR(length=128), nullable=False),
    sa.Column('rating', sa.NUMERIC(precision=3, scale=2), nullable=False),
    sa.Column('mal_ranking', sa.INTEGER(), nullable=False),
    sa.Column('members', sa.BIGINT(), server_default=sa.text('0'), nullable=False),
    sa.Column('synposis', sa.TEXT(), nullable=False),
    sa.CheckConstraint('mal_ranking >= 0', name='check_ranking_positive'),
    sa.CheckConstraint('members >= 0', name='check_members_positive'),
    sa.CheckConstraint('rating >= 0', name='check_rating_positive'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('animes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_animes_title'), ['title'], unique=True)

    op.create_table('genres',
    sa.Column('id', sa.SMALLINT(), autoincrement=True, nullable=False),
    sa.Column('_name', sa.VARCHAR(length=16), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('genres', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_genres__name'), ['_name'], unique=True)

    op.create_table('anime_genres',
    sa.Column('anime_id', sa.INTEGER(), nullable=False),
    sa.Column('genre_id', sa.SMALLINT(), nullable=False),
    sa.ForeignKeyConstraint(['anime_id'], ['animes.id'], ),
    sa.ForeignKeyConstraint(['genre_id'], ['genres.id'], ),
    sa.PrimaryKeyConstraint('anime_id', 'genre_id', name='pk_anime_genres')
    )
    op.create_table('stream_links',
    sa.Column('anime_id', sa.INTEGER(), nullable=False),
    sa.Column('url', sa.VARCHAR(length=256), nullable=False),
    sa.Column('website', sa.VARCHAR(length=64), nullable=False),
    sa.ForeignKeyConstraint(['anime_id'], ['animes.id'], ),
    sa.PrimaryKeyConstraint('anime_id', 'url', name='pk_stream_links')
    )
    with op.batch_alter_table('forums', schema=None) as batch_op:
        batch_op.add_column(sa.Column('anime', sa.INTEGER(), nullable=True))
        batch_op.create_index(batch_op.f('ix_forums_anime'), ['anime'], unique=False)
        batch_op.create_unique_constraint('uq_name_anime', ['_name', 'anime'])
        batch_op.create_foreign_key(None, 'animes', ['anime'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('forums', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint('uq_name_anime', type_='unique')
        batch_op.drop_index(batch_op.f('ix_forums_anime'))
        batch_op.drop_column('anime')

    op.drop_table('stream_links')
    op.drop_table('anime_genres')
    with op.batch_alter_table('genres', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_genres__name'))

    op.drop_table('genres')
    with op.batch_alter_table('animes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_animes_title'))

    op.drop_table('animes')
    # ### end Alembic commands ###
