"""empty message

Revision ID: eebbb200a4c1
Revises: c4b38d290ad6
Create Date: 2025-03-30 21:18:22.108833

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eebbb200a4c1'
down_revision = 'c4b38d290ad6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('forum_flairs',
    sa.Column('forum_id', sa.INTEGER(), nullable=False),
    sa.Column('flair_name', sa.VARCHAR(length=32), nullable=False),
    sa.ForeignKeyConstraint(['forum_id'], ['forums.id'], ),
    sa.PrimaryKeyConstraint('forum_id', 'flair_name', name='pk_forum_flairs')
    )
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('forum_id', sa.INTEGER(), nullable=False))
        batch_op.create_foreign_key(None, 'forums', ['forum_id'], ['id'])
        batch_op.drop_column('forum')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('forum', sa.VARCHAR(length=128), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('forum_id')

    op.drop_table('forum_flairs')
    # ### end Alembic commands ###
