"""empty message

Revision ID: f505901ccc85
Revises: eebbb200a4c1
Create Date: 2025-04-02 18:09:37.972437

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f505901ccc85'
down_revision = 'eebbb200a4c1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('author_id', sa.BIGINT(), nullable=False))
        batch_op.create_index(batch_op.f('ix_comments_author_id'), ['author_id'], unique=False)
        batch_op.create_foreign_key(None, 'users', ['author_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_comments_author_id'))
        batch_op.drop_column('author_id')

    # ### end Alembic commands ###
