repos:
  - repo: https://github.com/psf/black-pre-commit-mirror
    rev: 26.3.1
    hooks:
      - id: black
        name: black
        entry: black
        language: python
        types_or: [python, pyi]

  - repo: local
    hooks:
      - id: autoflake
        name: autoflake
        language: script
        types_or: [python, pyi]
        entry: .pre-commit/autoflake_runner.bash

  - repo: https://github.com/hhatto/autopep8
    rev: v2.3.2
    hooks:
    - id: autopep8
      types_or: [python, pyi]


  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: trailing-whitespace
      - id: check-ast
      - id: check-json
      - id: check-toml
      - id: check-yaml
      - id: double-quote-string-fixer
      - id: end-of-file-fixer
      - id: fix-byte-order-marker
      - id: trailing-whitespace

  - repo: https://github.com/gitleaks/gitleaks
    rev: v8.24.2
    hooks:
      - id: gitleaks
