name: tenjin
services:
  # Edge APIs
  resource_server:
    build:
      context: .
      dockerfile: resource_server/Dockerfile

    depends_on:
    - resource_server_database
    - resource_server_redis

    networks:
      - postgres_network
      - redis_network

    ports:
      - '80:80'

  x-resource-base: &resource-base
    build: ./resource_server
    environment:
      - WORKER_POSTGRES_USERNAME=${WORKER_POSTGRES_USERNAME}
       -WORKER_POSTGRES_PASSWORD=${WORKER_POSTGRES_PASSWORD}
    networks:
      - redis_network
      - postgres_network
    depends_on:
      - resource_server
      - resource_server_redis
      - resource_server_database
    restart: unless-stopped

  mail:
    <<: *resource-base
    command: python3 scripts/mail.py

  database_counter_worker:
    <<: *resource-base
    command: python3 scripts/batch_workers/counter.py

  database_insert_worker:
    <<: *resource-base
    command: python3 scripts/batch_workers/insert.py

  database_soft_delete_worker:
    <<: *resource-base
    command: python3 scripts/batch_workers/soft_delete.py

  database_user_activity_delete:
    <<: *resource-base
    command: python3 scripts/batch_workers/user_activity_delete.py

  database_user_activity_recovery_worker:
    <<: *resource-base
    command: python3 scripts/batch_workers/user_activity_recovery.py

  database_weak_delete_worker:
    <<: *resource-base
    command: python3 scripts/batch_workers/weak_delete.py

  database_weak_inserts_worker:
    <<: *resource-base
    command: python3 scripts/batch_workers/weak_insert.py

  auth_server:
    build:
      context: .
      dockerfile: auth_server/Dockerfile
    
    depends_on:
      - auth_server_synced_store
      - auth_server_key_store
      - auth_server_database

    networks:
      - postgres_network
      - redis_network
    ports:
      - '8080:8080'

  # Redis

  resource_server_redis:
    image: 'redis:8'
    command: redis-server /usr/local/etc/redis/redis.conf
    networks:
      - redis_network

    volumes:
    - ./resource_server/instance/redis.conf:/usr/local/etc/redis/redis.conf:ro
    - ./resource_server/instance/users.acl:/usr/local/etc/redis/users.acl:ro

  auth_server_synced_store:
    image: 'redis:8'
    command: redis-server /usr/local/etc/redis/redis.conf
    networks:
      - redis_network
    
    volumes:
      - ./auth_server/instance/redis.conf:/usr/local/etc/redis/redis.conf:ro
      - ./auth_server/instance/users.acl:/usr/local/etc/redis/users.acl:ro

  auth_server_key_store:
    image: 'redis:8'
    command: redis-server /usr/local/etc/redis/redis.conf
    networks:
      - redis_network

    volumes:
      - ./auth_server/instance/redis.conf:/usr/local/etc/redis/redis.conf:ro
      - ./auth_server/instance/users.acl:/usr/local/etc/redis/users.acl:ro

  # Databases
  resource_server_database:
    image: 'postgres:17.9'
    networks:
      - postgres_network
    volumes:
      - resource_server_data:/var/lib/postgresql/data
      - ./resource_server/authz/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - POSTGRES_USER=${MASTER_RESOURCE_SERVER_POSTGRES_USERNAME}
      - POSTGRES_PASSWORD=${MASTER_RESOURCE_SERVER_POSTGRES_PASSWORD}
      - POSTGRES_DB=${RESOURCE_DB_NAME}
      - RESOURCE_SERVER_POSTGRES_USERNAME=${RESOURCE_SERVER_POSTGRES_USERNAME}
      - RESOURCE_SERVER_POSTGRES_PASSWORD=${RESOURCE_SERVER_POSTGRES_PASSWORD}
      - WORKER_POSTGRES_USERNAME=${WORKER_POSTGRES_USERNAME}
      - WORKER_POSTGRES_PASSWORD=${WORKER_POSTGRES_PASSWORD}
    restart: on-failure[3]
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${MASTER_RESOURCE_SERVER_POSTGRES_USERNAME}"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
      
  auth_server_database:
    image: 'postgres:17.9'
    networks:
      - postgres_network
    volumes:
      - auth_server_data:/var/lib/postgresql/data
      - ./auth_server/authz/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - POSTGRES_USER=${MASTER_AUTH_SERVER_POSTGRES_USERNAME}
      - POSTGRES_PASSWORD=${MASTER_AUTH_SERVER_POSTGRES_PASSWORD}
      - POSTGRES_DB=${AUTH_DB_NAME}
      - AUTH_SERVER_POSTGRES_USERNAME=${AUTH_SERVER_POSTGRES_USERNAME}
      - AUTH_SERVER_POSTGRES_PASSWORD=${AUTH_SERVER_POSTGRES_PASSWORD}
    restart: on-failure[3]
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${MASTER_AUTH_SERVER_POSTGRES_USERNAME}"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

networks:
  postgres_network:
  redis_network:

volumes:
  auth_server_data:
  resource_server_data: