[project]
name = "tenjin"
version = "1.0.0"
description = "Tenjin"
readme = "README.md"
requires-python = ">=3.13, <3.14"
dependencies = [
    "ruff>=0.16.7",
]

[tool.uv.workspace]
members = [
    "auth_server",
    "auxillary",
    "resource_auxillary",
    "resource_database_workers",
    "resource_server",
    "email_worker",
]

[dependency-groups]
dev = [
    "bandit[baseline,toml]>=1.9.4",
    "deptry>=0.25.1",
    "orjson>=3.11.9",
    "pre-commit>=4.6.0",
    "pytest>=9.1.1",
    "pytest-asyncio>=1.4.0",
    "pytest-mock>=3.15.1",
]

[tool.bandit]
skips=[
    "B201",
    "B507",
    "B610",
    "B611",
    "B614",
    "B615",
    "B703",
]
exclude_dirs=[
    ".venv",
    ".pre-commit/utilities"
]


[tool.deptry]
known_first_party=[
    "auth_server",
    "auxillary",
    "resource_auxillary",
    "resource_database_workers",
    "resource_server"
]

[tool.pyrefly]
project-excludes=[
    "**/alembic"
]

[tool.ruff]
target-version = "py313"
line-length = 88

[tool.ruff.lint]
select = [
    "E4", "E7", "E9",
    "F",
    "I",
    "N",
    "B0",
    "DTZ",
    "RET",
    "ASYNC",
    "PERF101",
    "PERF102",
    # "PERF401"
    # "PERF402",
    # "PERF403",
    "SIM101",
    "SIM102",
    "SIM109",
    "SIM110",
    "SIM114",
    "SIM115",
    "SIM300",
    "SIM401"
]

ignore = [
    "B008", "B009", "B010", "B013", "B019", "B043", "E741", "E731"
]

[tool.ruff.lint.per-file-ignores]
"**/__init__.py" = ["F401"]
"**/gunicorn.conf.py" = ["N999"]

[tool.ruff.format]
quote-style = "double"
indent-style = "space"
skip-magic-trailing-comma = false
line-ending = "auto"
docstring-code-format = false
