[project]
name = "tenjin"
version = "1.0.0"
description = "Tenjin"
readme = "README.md"
requires-python = ">=3.13, <3.14"

[tool.uv.workspace]
members = [
    "auth_server",
    "auxillary",
    "resource_auxillary",
    "resource_database_workers",
    "resource_server",
    "email_worker",
]

[dependency-groups]
dev = [
    "autoflake>=2.3.3",
    "bandit[baseline,toml]>=1.9.4",
    "black>=26.3.1",
    "deptry>=0.25.1",
    "orjson>=3.11.9",
    "pre-commit>=4.6.0",
]

[tool.bandit]
skips=[
    "B201",
    "B507",
    "B610",
    "B611",
    "B614",
    "B615",
    "B703",
]
exclude_dirs=[
    ".venv",
    ".pre-commit/utilities"
]


[tool.deptry]
known_first_party=[
    "auth_server",
    "auxillary",
    "resource_auxillary",
    "resource_database_workers",
    "resource_server"
]
