[core]
APPLICATION_ROOT="/api/v1"
PORT=8000

AUTH_SERVER_NAME="auth_server"


[database]
POSTGRES_HOST="127.0.0.1"
POSTGRES_PORT=5432
POSTGRES_DATABASE="resource_db"


[database.SQLALCHEMY]
SQLALCHEMY_POOL_SIZE=16
SQLALCHEMY_MAX_OVERFLOW=8
SQLALCHEMY_POOL_RECYCLE=600
SQLALCHEMY_POOL_TIMEOUT=15
SQLALCHEMY_TRACK_MODIFICATIONS=false


[redis]
HOST="127.0.0.1"
PORT=6379
DB=0


[cache]
TTL_CAP=86400
TTL_PROMOTION=15
TTL_STRONGEST=1200
TTL_STRONG=600
TTL_WEAK=300
TTL_EPHEMERAL=60

NF_SENTINEL_KEY="__NF__"
NF_SENTINEL_VALUE="1"

RESOURCE_CREATION_PENDING_FLAG="flag:cp"
RESOURCE_DELETION_PENDING_FLAG="flag:dp"
RESOURCE_CREATION_PENDING_ALT_FLAG="flag:cpa"


[jwks]
JWKS_ENDPOINT="/api/v1/auth/jwks.json"
JWKS_REQUEST_TIMEOUT=3
JWKS_POLL_INTERVAL=1800
UPDATION_LOCK_LIFESPAN=300

KEY_ANNOUNCEMENT_DURATION=300
MAX_GLOBAL_MAPPING_POLLS=10
GLOBAL_MAPPING_POLL_INTERVAL=2
SLAVE_WAIT_INTERVAL=5

KEY_LEEWAY=3                    # minutes
ALLOWED_ALGORITHMS=["ES256"]


[business]
ACCOUNT_RECOVERY_PERIOD=7       # days
PASSWORD_TOKEN_MAX_AGE=15       # minutes
ACCOUNT_AUDIT_THRESHOLD=2       # days
