"""empty message

Revision ID: 145e5f8b6b8e
Revises: c7a66e3e52c8
Create Date: 2025-05-26 13:11:27.023112

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '145e5f8b6b8e'
down_revision = 'c7a66e3e52c8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('admins', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_by', sa.INTEGER(), nullable=True))
        batch_op.create_foreign_key(None, 'admins', ['created_by'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('admins', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('created_by')

    # ### end Alembic commands ###
