"""empty message

Revision ID: 81dad9fdafa0
Revises: 8922706208e1
Create Date: 2025-05-25 20:06:43.666570

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '81dad9fdafa0'
down_revision = '8922706208e1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('admins', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password_hash', postgresql.BYTEA(), nullable=False))
        batch_op.add_column(sa.Column('password_salt', postgresql.BYTEA(), nullable=False))
        batch_op.drop_column('password')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('admins', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password', postgresql.BYTEA(), autoincrement=False, nullable=False))
        batch_op.drop_column('password_salt')
        batch_op.drop_column('password_hash')

    # ### end Alembic commands ###
