"""empty message

Revision ID: 8922706208e1
Revises: 
Create Date: 2025-05-25 17:29:23.545518

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '8922706208e1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('admins', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password', postgresql.BYTEA(), nullable=False))
        batch_op.add_column(sa.Column('time_deleted', sa.TIMESTAMP(), server_default=sa.text('null'), nullable=True))
        batch_op.add_column(sa.Column('last_login', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('admins', schema=None) as batch_op:
        batch_op.drop_column('last_login')
        batch_op.drop_column('time_deleted')
        batch_op.drop_column('password')

    # ### end Alembic commands ###
