"""empty message

Revision ID: 8e0c657d6685
Revises: 145e5f8b6b8e
Create Date: 2025-05-26 23:07:57.265593

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8e0c657d6685'
down_revision = '145e5f8b6b8e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('keydata', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rotated_by', sa.INTEGER(), nullable=True))
        batch_op.drop_index('ix_keydata_manual_rotation')
        batch_op.create_index(batch_op.f('ix_keydata_rotated_by'), ['rotated_by'], unique=False)
        batch_op.create_foreign_key(None, 'admins', ['rotated_by'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('keydata', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_keydata_rotated_by'))
        batch_op.create_index('ix_keydata_manual_rotation', ['manual_rotation'], unique=False)
        batch_op.drop_column('rotated_by')

    # ### end Alembic commands ###
