"""empty message

Revision ID: c7a66e3e52c8
Revises: 81dad9fdafa0
Create Date: 2025-05-26 10:39:23.459406

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c7a66e3e52c8'
down_revision = '81dad9fdafa0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('admins', schema=None) as batch_op:
        batch_op.add_column(sa.Column('locked', sa.BOOLEAN(), server_default=sa.text('false'), nullable=False))

    with op.batch_alter_table('suspicious_activities', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.VARCHAR(length=64), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('suspicious_activities', schema=None) as batch_op:
        batch_op.drop_column('description')

    with op.batch_alter_table('admins', schema=None) as batch_op:
        batch_op.drop_column('locked')

    # ### end Alembic commands ###
