\getenv RESOURCE_DB_NAME RESOURCE_DB_NAME
\getenv RESOURCE_SERVER_POSTGRES_USERNAME RESOURCE_SERVER_POSTGRES_USERNAME
\getenv RESOURCE_SERVER_POSTGRES_PASSWORD RESOURCE_SERVER_POSTGRES_PASSWORD

\getenv WORKER_POSTGRES_USERNAME WORKER_POSTGRES_USERNAME
\getenv WORKER_POSTGRES_PASSWORD WORKER_POSTGRES_PASSWORD

CREATE DATABASE :"RESOURCE_DB_NAME";

\c :"RESOURCE_DB_NAME"

-- Resource server user
CREATE USER :"RESOURCE_SERVER_POSTGRES_USERNAME"
WITH PASSWORD :'RESOURCE_SERVER_POSTGRES_PASSWORD';

GRANT CONNECT ON DATABASE :"RESOURCE_DB_NAME"
TO :"RESOURCE_SERVER_POSTGRES_USERNAME";

ALTER DEFAULT PRIVILEGES IN SCHEMA public
GRANT SELECT ON TABLES TO :"RESOURCE_SERVER_POSTGRES_USERNAME";

GRANT SELECT ON ALL TABLES IN SCHEMA public
TO :"RESOURCE_SERVER_POSTGRES_USERNAME";

GRANT DELETE ON users, password_recovery_tokens
TO :"RESOURCE_SERVER_POSTGRES_USERNAME";

GRANT INSERT ON forums, forum_admins, users, password_recovery_tokens
TO :"RESOURCE_SERVER_POSTGRES_USERNAME";

GRANT UPDATE (title, description) ON forums TO :"RESOURCE_SERVER_POSTGRES_USERNAME";
GRANT UPDATE (role) ON forum_admins TO :"RESOURCE_SERVER_POSTGRES_USERNAME";
GRANT UPDATE (closed, body_text, title) ON posts TO :"RESOURCE_SERVER_POSTGRES_USERNAME";
GRANT UPDATE (rtbf, pw_hash, pw_salt, last_login) ON users TO :"RESOURCE_SERVER_POSTGRES_USERNAME";

-- Batch Worker
CREATE USER :"WORKER_POSTGRES_USERNAME"
WITH PASSWORD :'WORKER_POSTGRES_PASSWORD';

GRANT CONNECT ON DATABASE :"RESOURCE_DB_NAME"
TO :"WORKER_POSTGRES_USERNAME";

GRANT SELECT ON ALL TABLES IN SCHEMA public
TO :"WORKER_POSTGRES_USERNAME";

ALTER DEFAULT PRIVILEGES IN SCHEMA public
GRANT SELECT ON TABLES TO :"WORKER_POSTGRES_USERNAME";

GRANT UPDATE (score, total_comments, reports, saves) ON posts TO :"WORKER_POSTGRES_USERNAME";
GRANT UPDATE (score, reports) ON comments TO :"WORKER_POSTGRES_USERNAME";
GRANT UPDATE (members) ON animes TO :"WORKER_POSTGRES_USERNAME";
GRANT UPDATE (deleted_at, deleted, rtbf, aura, total_posts, total_comments) ON users TO :"WORKER_POSTGRES_USERNAME";

GRANT DELETE ON posts, comments, forums,
post_votes, post_saves, post_reports,
comment_votes, comment_reports
TO :"WORKER_POSTGRES_USERNAME";

GRANT INSERT ON posts, comments, forums,
post_votes, post_saves, post_reports,
comment_votes, comment_reports
TO :"WORKER_POSTGRES_USERNAME";
