#!/bin/bash
set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
    CREATE USER "$RESOURCE_SERVER_POSTGRES_USERNAME" WITH PASSWORD '$RESOURCE_SERVER_POSTGRES_PASSWORD';
    CREATE USER "$WORKER_POSTGRES_USERNAME" WITH PASSWORD '$WORKER_POSTGRES_PASSWORD';

    GRANT CONNECT ON DATABASE "$POSTGRES_DB" TO "$RESOURCE_SERVER_POSTGRES_USERNAME";
    GRANT CONNECT ON DATABASE "$POSTGRES_DB" TO "$WORKER_POSTGRES_USERNAME";
    GRANT USAGE ON SCHEMA public TO "$RESOURCE_SERVER_POSTGRES_USERNAME";
    GRANT USAGE ON SCHEMA public TO "$WORKER_POSTGRES_USERNAME";

    ALTER DEFAULT PRIVILEGES FOR ROLE "$POSTGRES_USER" IN SCHEMA public 
    GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO "$RESOURCE_SERVER_POSTGRES_USERNAME";

    ALTER DEFAULT PRIVILEGES FOR ROLE "$POSTGRES_USER" IN SCHEMA public 
    GRANT SELECT, INSERT, UPDATE ON TABLES TO "$WORKER_POSTGRES_USERNAME";

    ALTER DEFAULT PRIVILEGES FOR ROLE "$POSTGRES_USER" IN SCHEMA public 
    GRANT USAGE, SELECT, UPDATE ON SEQUENCES TO "$RESOURCE_SERVER_POSTGRES_USERNAME";
    
    ALTER DEFAULT PRIVILEGES FOR ROLE "$POSTGRES_USER" IN SCHEMA public 
    GRANT USAGE, SELECT, UPDATE ON SEQUENCES TO "$WORKER_POSTGRES_USERNAME";
EOSQL