hostname="email_worker"
port=10_000
use_tls=true

[worker]
MAX_RETRIES=2

DLQ_NAME="DLQ"

CONSUMER_READ_INTERVAL=500                      # milliseconds
CONSUMER_READ_SIZE=1000
CONSUMER_BLOCK_TIME=500                         # milliseconds
CONSUMER_GROUP_NAME="email_consumers"

IQ_CONSUMER_BASE_WAITING_TIME=2                     # seconds
IQ_CONSUMER_BATCH_SIZE_QUOTA=0.1
IQ_CONSUMER_GET_TIMEOUT=0.1                         # seconds
IQ_CONSUMER_SLEEP_INTERVAL=0.01                     # seconds

RECLAIM_THRESHOLD=120_000                           # milliseconds
RECLAIMATION_CHECK_INTERVAL=30_000                  # milliseconds
MAX_DELIVERIES=3

MAXIMUM_BACKOFF_INTERVAL=0.08                       # seconds
BASE_BACKOFF_INTERVAL=0.005                         # seconds
BACKOFF_EXPONENTIAL=2

GRACEFUL_SHUTDOWN_PERIOD=10                         # seconds
