from enum import StrEnum


class StreamName(StrEnum):
    INSERTIONS = "INSERTIONS"
    WEAK_INSERTIONS = "WEAK_INSERTIONS"
    COUNTER = "COUNTER"
    SOFT_DELETE = "SOFT_DELETE"
    WEAK_DELETE = "WEAK_DELETE"
    USER_ACTIVITY_DELETE = "USER_ACTIVITY_DELETE"
    USER_ACTIVITY_RECOVER = "USER_ACTIVITY_RECOVER"
