from enum import StrEnum
from typing import Final, LiteralString

NAME_SEPERATOR: Final[LiteralString] = ":"

MALFORMED_EVENT_PREFIX: Final[LiteralString] = "MALFORMED"


class IntentFlag(StrEnum):
    RESOURCE_CREATION_PENDING_FLAG = NAME_SEPERATOR.join(("FLAG", "C"))
    RESOURCE_CREATION_PENDING_ALT_FLAG = NAME_SEPERATOR.join(("FLAG", "CA"))
    RESOURCE_DELETION_PENDING_FLAG = NAME_SEPERATOR.join(("FLAG", "D"))


class StreamName(StrEnum):
    POSTS = "POSTS"
    COMMENTS = "COMMENTS"
    FORUMS = "FORUMS"
    ANIMES = "ANIMES"
    USERS = "USERS"
    DOWNSTREAM_DELETIONS = "DOWNSTREAM_DELETIONS"
    DOWNSTREAM_COUNTER_DECREMENTS = "DOWNSTREAM_COUNTER_DECREMENTS"
    USER_EMAILS = "USER_EMAILS"


class Action(StrEnum):
    SAVE = "SAVE"
    REPORT = "REPORT"
    VOTE = "VOTE"
    UNVOTE = "UNVOTE"
    SUB = "SUB"
    UNSUB = "UNSUB"
    DELETE = "DELETE"
    CREATE = "CREATE"


class EventName(StrEnum):
    POST_CREATE = "POST_CREATE"
    POST_SAVE = "POST_SAVE"
    POST_UNSAVE = "POST_UNSAVE"
    POST_REPORT = "POST_REPORT"
    POST_VOTE = "POST_VOTE"  # Covers both upvote and downvote
    POST_UNVOTE = "POST_UNVOTE"
    POST_DELETE = "POST_DELETE"

    ANIME_SUB = "ANIME_SUB"
    ANIME_UNSUB = "ANIME_UNSUB"

    COMMENT_CREATE = "COMMENT_CREATE"
    COMMENT_VOTE = "COMMENT_VOTE"  # Covers both upvote and downvote
    COMMENT_UNVOTE = "COMMENT_UNVOTE"
    COMMENT_REPORT = "COMMENT_REPORT"
    COMMENT_DELETE = "COMMENT_DELETE"

    FORUM_SUB = "FORUM_SUB"
    FORUM_UNSUB = "FORUM_UNSUB"

    USER_CLEANUP = "USER_CLEANUP"

    MALFORMED = "MALFORMED"

    ORPHANED_POST_DELETE = "ORPHANED_POST_DELETE"
    ORPHANED_COMMENT_DELETE = "ORPHANED_COMMENT_DELETE"

    DOWNSTREAM_POST_DECREMENT = "DOWNSTREAM_POST_DECREMENT"
    DOWNSTREAM_COMMENT_DECREMENT = "DOWNSTREAM_COMMENT_DECREMENT"
