[core]
APPLICATION_ROOT="/api/v1"
PORT=8080

[jwks]
JWKS_FILENAME="jwks.json"
JWKS_CAP=3

[jwks.token_manager]
REFRESH_LIFETIME=10800      # seconds
ACCESS_LIFETIME=1800        # seconds
LEEWAY=180                  # seconds
ALG="ES256"
MAX_TOKENS_PER_FAMILY=3
ANNOUNCEMENT_DURATION=10800 # seconds
POLL_INTERVAL=30            # seconds

[redis]
[redis.synced_store]
HOST="auth_server_redis"
PORT=6380
DB=0
DECODE_RESPONSES=true

[redis.token_store]
HOST="auth_server_redis"
PORT=6380
DB=1
DECODE_RESPONSES=true

[database]
POSTGRES_HOST="auth_server_database"
POSTGRES_PORT=5432
POSTGRES_DATABASE="auth_db"

[database.sqlalchemy]
SQLALCHEMY_POOL_SIZE=20
SQLALCHEMY_MAX_OVERFLOW=10
SQLALCHEMY_POOL_RECYCLE=600
SQLALCHEMY_POOL_TIMEOUT=15
SQLALCHEMY_TRACK_MODIFICATIONS=0

[keys]
MAX_VALID_KEYS=3
KEY_ROTATION_COOLDOWN=86400
KEY_IDENTIFIER_LENGTH=64

[admin]
SUSPICIOUS_LOOKBACK_TIME=86400
MAX_ACTIVITY_LIMIT=5
ADMIN_SESSION_DURATION=900
MAX_SESSION_ITERATIONS=5
REVIVAL_DIGEST_LENGTH=256

[bootup]
SLAVE_SLEEP_POLLING_INTERVAL=1
MASTER_BOOTUP_LOCK_LIFESPAN=300
