"""empty message

Revision ID: 09306c1baeae
Revises: 174235ccf672
Create Date: 2026-06-13 12:27:39.597911

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "09306c1baeae"
down_revision: Union[str, Sequence[str], None] = "174235ccf672"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "posts", "body_text", existing_type=sa.VARCHAR(length=32800), nullable=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "posts", "body_text", existing_type=sa.VARCHAR(length=32800), nullable=False
    )
    # ### end Alembic commands ###
