"""removes rtbf

Revision ID: 0a1370421a2b
Revises: ba411046cc75
Create Date: 2026-06-27 11:55:36.201126

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "0a1370421a2b"
down_revision: Union[str, Sequence[str], None] = "ba411046cc75"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("comments", "rtbf_hidden")
    op.drop_column("forums", "rtbf_hidden")
    op.drop_column("posts", "rtbf_hidden")
    op.drop_column("users", "rtbf")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column(
            "rtbf",
            sa.BOOLEAN(),
            server_default=sa.text("false"),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.add_column(
        "posts",
        sa.Column("rtbf_hidden", sa.BOOLEAN(), autoincrement=False, nullable=True),
    )
    op.add_column(
        "forums",
        sa.Column("rtbf_hidden", sa.BOOLEAN(), autoincrement=False, nullable=False),
    )
    op.add_column(
        "comments",
        sa.Column("rtbf_hidden", sa.BOOLEAN(), autoincrement=False, nullable=True),
    )
    # ### end Alembic commands ###
