"""empty message

Revision ID: 174235ccf672
Revises: 8f2bdc6314fd
Create Date: 2026-06-03 19:00:33.268599

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "174235ccf672"
down_revision: Union[str, Sequence[str], None] = "8f2bdc6314fd"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "user_tickets", sa.Column("email", sa.VARCHAR(length=254), nullable=False)
    )
    op.drop_index(op.f("ix_user_tickets_user_id"), table_name="user_tickets")
    op.drop_constraint(
        op.f("user_tickets_user_id_fkey"), "user_tickets", type_="foreignkey"
    )
    op.drop_column("user_tickets", "user_id")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "user_tickets",
        sa.Column("user_id", sa.BIGINT(), autoincrement=False, nullable=False),
    )
    op.create_foreign_key(
        op.f("user_tickets_user_id_fkey"), "user_tickets", "users", ["user_id"], ["id_"]
    )
    op.create_index(
        op.f("ix_user_tickets_user_id"), "user_tickets", ["user_id"], unique=False
    )
    op.drop_column("user_tickets", "email")
    # ### end Alembic commands ###
