"""empty message

Revision ID: 19ed1d233cb9
Revises: a9cdcdd416de
Create Date: 2026-06-23 11:14:21.969607

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "19ed1d233cb9"
down_revision: Union[str, Sequence[str], None] = "a9cdcdd416de"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("comment_votes", sa.Column("user_id", sa.BIGINT(), nullable=False))
    op.drop_constraint(
        op.f("comment_votes_voter_id_fkey"), "comment_votes", type_="foreignkey"
    )
    op.create_foreign_key(None, "comment_votes", "users", ["user_id"], ["id_"])
    op.drop_column("comment_votes", "voter_id")
    op.add_column(
        "comments", sa.Column("deletion_time", postgresql.TIMESTAMP(), nullable=True)
    )
    op.drop_column("comments", "time_deleted")
    op.add_column(
        "dlq_events",
        sa.Column(
            "failure_time",
            postgresql.TIMESTAMP(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
    )
    op.create_index(
        op.f("ix_dlq_events_failure_time"), "dlq_events", ["failure_time"], unique=False
    )
    op.add_column("forums", sa.Column("parent_anime", sa.INTEGER(), nullable=True))
    op.add_column(
        "forums", sa.Column("deletion_time", postgresql.TIMESTAMP(), nullable=True)
    )
    op.drop_index(op.f("ix_forums_anime"), table_name="forums")
    op.drop_constraint(op.f("uq_name_anime"), "forums", type_="unique")
    op.create_index(
        op.f("ix_forums_parent_anime"), "forums", ["parent_anime"], unique=False
    )
    op.create_unique_constraint("uq_forum_name", "forums", ["name_"])
    op.drop_constraint(op.f("forums_anime_fkey"), "forums", type_="foreignkey")
    op.create_foreign_key(None, "forums", "animes", ["parent_anime"], ["id_"])
    op.drop_column("forums", "anime")
    op.drop_column("forums", "time_deleted")
    op.add_column("post_votes", sa.Column("user_id", sa.BIGINT(), nullable=False))
    op.drop_constraint(
        op.f("post_votes_voter_id_fkey"), "post_votes", type_="foreignkey"
    )
    op.create_foreign_key(None, "post_votes", "users", ["user_id"], ["id_"])
    op.drop_column("post_votes", "voter_id")
    op.add_column("posts", sa.Column("parent_forum", sa.INTEGER(), nullable=False))
    op.add_column(
        "posts", sa.Column("deletion_time", postgresql.TIMESTAMP(), nullable=True)
    )
    op.drop_constraint(op.f("posts_forum_id_fkey"), "posts", type_="foreignkey")
    op.create_foreign_key(
        None, "posts", "forums", ["parent_forum"], ["id_"], ondelete="CASCADE"
    )
    op.drop_column("posts", "forum_id")
    op.drop_column("posts", "time_deleted")
    op.add_column("user_tickets", sa.Column("id_", sa.BIGINT(), nullable=False))
    op.drop_column("user_tickets", "id")
    op.add_column(
        "users", sa.Column("deletion_time", postgresql.TIMESTAMP(), nullable=True)
    )
    op.drop_column("users", "time_deleted")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column(
            "time_deleted", postgresql.TIMESTAMP(), autoincrement=False, nullable=True
        ),
    )
    op.drop_column("users", "deletion_time")
    op.add_column(
        "user_tickets", sa.Column("id", sa.BIGINT(), autoincrement=True, nullable=False)
    )
    op.drop_column("user_tickets", "id_")
    op.add_column(
        "posts",
        sa.Column(
            "time_deleted", postgresql.TIMESTAMP(), autoincrement=False, nullable=True
        ),
    )
    op.add_column(
        "posts",
        sa.Column("forum_id", sa.INTEGER(), autoincrement=False, nullable=False),
    )
    op.drop_constraint(None, "posts", type_="foreignkey")
    op.create_foreign_key(
        op.f("posts_forum_id_fkey"),
        "posts",
        "forums",
        ["forum_id"],
        ["id_"],
        ondelete="CASCADE",
    )
    op.drop_column("posts", "deletion_time")
    op.drop_column("posts", "parent_forum")
    op.add_column(
        "post_votes",
        sa.Column("voter_id", sa.BIGINT(), autoincrement=False, nullable=False),
    )
    op.drop_constraint(None, "post_votes", type_="foreignkey")
    op.create_foreign_key(
        op.f("post_votes_voter_id_fkey"), "post_votes", "users", ["voter_id"], ["id_"]
    )
    op.drop_column("post_votes", "user_id")
    op.add_column(
        "forums",
        sa.Column(
            "time_deleted", postgresql.TIMESTAMP(), autoincrement=False, nullable=True
        ),
    )
    op.add_column(
        "forums", sa.Column("anime", sa.INTEGER(), autoincrement=False, nullable=True)
    )
    op.drop_constraint(None, "forums", type_="foreignkey")
    op.create_foreign_key(
        op.f("forums_anime_fkey"), "forums", "animes", ["anime"], ["id_"]
    )
    op.drop_constraint("uq_forum_name", "forums", type_="unique")
    op.drop_index(op.f("ix_forums_parent_anime"), table_name="forums")
    op.create_unique_constraint(
        op.f("uq_name_anime"),
        "forums",
        ["name_", "anime"],
        postgresql_nulls_not_distinct=False,
    )
    op.create_index(op.f("ix_forums_anime"), "forums", ["anime"], unique=False)
    op.drop_column("forums", "deletion_time")
    op.drop_column("forums", "parent_anime")
    op.drop_index(op.f("ix_dlq_events_failure_time"), table_name="dlq_events")
    op.drop_column("dlq_events", "failure_time")
    op.add_column(
        "comments",
        sa.Column(
            "time_deleted", postgresql.TIMESTAMP(), autoincrement=False, nullable=True
        ),
    )
    op.drop_column("comments", "deletion_time")
    op.add_column(
        "comment_votes",
        sa.Column("voter_id", sa.BIGINT(), autoincrement=False, nullable=False),
    )
    op.drop_constraint(None, "comment_votes", type_="foreignkey")
    op.create_foreign_key(
        op.f("comment_votes_voter_id_fkey"),
        "comment_votes",
        "users",
        ["voter_id"],
        ["id_"],
    )
    op.drop_column("comment_votes", "user_id")
    # ### end Alembic commands ###
