"""adds_dlq_table

Revision ID: 33fe0a168e0a
Revises: ed06aa294747
Create Date: 2026-06-18 12:45:31.542079

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "33fe0a168e0a"
down_revision: Union[str, Sequence[str], None] = "ed06aa294747"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "dlq_events",
        sa.Column("event_id", sa.TEXT(), nullable=False),
        sa.Column(
            "acknowledgement_time",
            postgresql.TIMESTAMP(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.PrimaryKeyConstraint("event_id"),
    )
    op.create_index(
        op.f("ix_dlq_events_acknowledgement_time"),
        "dlq_events",
        ["acknowledgement_time"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_dlq_events_acknowledgement_time"), table_name="dlq_events")
    op.drop_table("dlq_events")
    # ### end Alembic commands ###
