"""Adds downstream deletions and decrements side-effects tables

Revision ID: 4a987efb72d6
Revises: f8e3eade649c
Create Date: 2026-09-07 18:49:19.234923

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "4a987efb72d6"
down_revision: Union[str, Sequence[str], None] = "f8e3eade649c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("cache_side_effects")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "cache_side_effects",
        sa.Column("event_id", sa.TEXT(), autoincrement=False, nullable=False),
        sa.Column(
            "side_effects_emitted", sa.BOOLEAN(), autoincrement=False, nullable=False
        ),
        sa.Column(
            "side_effects_payload",
            postgresql.JSONB(astext_type=sa.Text()),
            autoincrement=False,
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["event_id"],
            ["stream_events.event_id"],
            name=op.f("cache_side_effects_event_id_fkey"),
        ),
        sa.PrimaryKeyConstraint("event_id", name=op.f("cache_side_effects_pkey")),
    )
    # ### end Alembic commands ###
