"""Changes password_recovery_tokens.url_hash to varchar

Revision ID: 4bd0490dba29
Revises: 09306c1baeae
Create Date: 2026-06-13 15:54:33.099159

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "4bd0490dba29"
down_revision: Union[str, Sequence[str], None] = "09306c1baeae"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "password_recovery_tokens",
        "url_hash",
        existing_type=postgresql.BYTEA(),
        type_=sa.VARCHAR(length=512),
        existing_nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "password_recovery_tokens",
        "url_hash",
        existing_type=sa.VARCHAR(length=512),
        type_=postgresql.BYTEA(),
        existing_nullable=False,
    )
    # ### end Alembic commands ###
