"""Adds cache invalidation side-effects table

Revision ID: 4f0e730c41f9
Revises: 4a987efb72d6
Create Date: 2026-09-09 16:34:51.067855

"""

from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = "4f0e730c41f9"
down_revision: Union[str, Sequence[str], None] = "4a987efb72d6"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###
