"""makes synposis TEXT type

Revision ID: 59925fd514af
Revises: a639269cddd3
Create Date: 2026-07-03 12:42:37.662173

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "59925fd514af"
down_revision: Union[str, Sequence[str], None] = "a639269cddd3"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "animes",
        "synopsis",
        existing_type=sa.VARCHAR(length=256),
        type_=sa.TEXT(),
        existing_nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "animes",
        "synopsis",
        existing_type=sa.TEXT(),
        type_=sa.VARCHAR(length=256),
        existing_nullable=False,
    )
    # ### end Alembic commands ###
