"""updates stream_links PK

Revision ID: 61d4992fd845
Revises: e68d3c222782
Create Date: 2026-09-27 01:13:22.257887

"""

from typing import Sequence, Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "61d4992fd845"
down_revision: Union[str, Sequence[str], None] = "e68d3c222782"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("stream_links", "anime_id", nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("stream_links", "anime_id", nullable=True)
    # ### end Alembic commands ###
