"""adds_failed_side_effects_table

Revision ID: 76d4417ceeb6
Revises: 59925fd514af
Create Date: 2026-07-14 17:59:41.623357

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "76d4417ceeb6"
down_revision: Union[str, Sequence[str], None] = "59925fd514af"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "side_effects_dlq",
        sa.Column("id_", sa.BIGINT(), autoincrement=True, nullable=False),
        sa.Column("event_id", sa.BIGINT(), nullable=False),
        sa.Column(
            "side_effect_type",
            postgresql.ENUM(
                "CACHE_INVALIDATION",
                "INTENT_INVALIDATION",
                "COUNTER_UPDATE",
                name="SIDE_EFFECTS_TYPES",
            ),
            nullable=False,
        ),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.PrimaryKeyConstraint("id_"),
    )
    op.create_index(
        op.f("ix_side_effects_dlq_event_id"),
        "side_effects_dlq",
        ["event_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_side_effects_dlq_side_effect_type"),
        "side_effects_dlq",
        ["side_effect_type"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_side_effects_dlq_side_effect_type"), table_name="side_effects_dlq"
    )
    op.drop_index(op.f("ix_side_effects_dlq_event_id"), table_name="side_effects_dlq")
    op.drop_table("side_effects_dlq")
    # ### end Alembic commands ###
