"""init

Revision ID: 8f2bdc6314fd
Revises:
Create Date: 2026-06-03 10:26:36.225169

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "8f2bdc6314fd"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "animes",
        sa.Column("id_", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("title", sa.VARCHAR(length=64), nullable=False),
        sa.Column("rating", sa.NUMERIC(precision=3, scale=2), nullable=False),
        sa.Column("mal_rating", sa.INTEGER(), nullable=True),
        sa.Column("members", sa.BIGINT(), server_default=sa.text("0"), nullable=False),
        sa.Column("synopsis", sa.VARCHAR(length=256), nullable=False),
        sa.CheckConstraint("mal_rating >= 0", name="check_ranking_positive"),
        sa.CheckConstraint("members >= 0", name="check_members_positive"),
        sa.CheckConstraint("rating <= 10", name="check_rating_upperbound"),
        sa.CheckConstraint("rating >= 0", name="check_rating_positive"),
        sa.PrimaryKeyConstraint("id_"),
        sa.UniqueConstraint("title"),
    )
    op.create_table(
        "genres",
        sa.Column("id_", sa.SMALLINT(), autoincrement=True, nullable=False),
        sa.Column("name_", sa.VARCHAR(length=16), nullable=False),
        sa.CheckConstraint("length(name_) > 4"),
        sa.PrimaryKeyConstraint("id_"),
        sa.UniqueConstraint("name_"),
    )
    op.create_table(
        "users",
        sa.Column("id_", sa.BIGINT(), autoincrement=True, nullable=False),
        sa.Column("username", sa.VARCHAR(length=64), nullable=False),
        sa.Column("email", sa.VARCHAR(length=254), nullable=False),
        sa.Column(
            "rtbf", sa.BOOLEAN(), server_default=sa.text("false"), nullable=False
        ),
        sa.Column("pw_hash", postgresql.BYTEA(length=60), nullable=False),
        sa.Column("aura", sa.BIGINT(), server_default=sa.text("0"), nullable=False),
        sa.Column(
            "total_posts", sa.INTEGER(), server_default=sa.text("0"), nullable=False
        ),
        sa.Column(
            "total_comments", sa.INTEGER(), server_default=sa.text("0"), nullable=False
        ),
        sa.Column(
            "time_joined",
            postgresql.TIMESTAMP(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.Column("last_login", postgresql.TIMESTAMP(), nullable=False),
        sa.Column(
            "deleted", sa.BOOLEAN(), server_default=sa.text("false"), nullable=False
        ),
        sa.Column("time_deleted", postgresql.TIMESTAMP(), nullable=True),
        sa.CheckConstraint(
            "email ~ 're.compile(''^[a-zA-Z0-9._%%+\\\\-]+@[a-zA-Z0-9.\\\\-]+\\\\.[a-zA-Z]{2,}$'')'",
            name="check_email_regex",
        ),
        sa.CheckConstraint("length(email) >= 5"),
        sa.CheckConstraint("length(username) >= 4", name="ck_users_username_length"),
        sa.PrimaryKeyConstraint("id_"),
        sa.UniqueConstraint("email"),
        sa.UniqueConstraint("username"),
    )
    op.create_table(
        "anime_genres",
        sa.Column("anime_id", sa.INTEGER(), nullable=False),
        sa.Column("genre_id", sa.SMALLINT(), nullable=False),
        sa.ForeignKeyConstraint(["anime_id"], ["animes.id_"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["genre_id"], ["genres.id_"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("anime_id", "genre_id"),
    )
    op.create_table(
        "anime_subscriptions",
        sa.Column("user_id", sa.BIGINT(), nullable=False),
        sa.Column("anime_id", sa.INTEGER(), nullable=False),
        sa.Column(
            "time_subscribed",
            postgresql.TIMESTAMP(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["anime_id"], ["animes.id_"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id_"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("user_id", "anime_id"),
    )
    op.create_table(
        "forums",
        sa.Column("id_", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("name_", sa.VARCHAR(length=64), nullable=False),
        sa.Column("anime", sa.INTEGER(), nullable=True),
        sa.Column("description", sa.VARCHAR(length=256), nullable=True),
        sa.Column(
            "subscribers", sa.BIGINT(), server_default=sa.text("0"), nullable=False
        ),
        sa.Column("posts", sa.BIGINT(), server_default=sa.text("0"), nullable=False),
        sa.Column("created_at", postgresql.TIMESTAMP(), nullable=False),
        sa.Column(
            "admin_count", sa.SMALLINT(), server_default=sa.text("1"), nullable=False
        ),
        sa.Column(
            "deleted", sa.BOOLEAN(), server_default=sa.text("false"), nullable=False
        ),
        sa.Column("time_deleted", postgresql.TIMESTAMP(), nullable=True),
        sa.Column("rtbf_hidden", sa.BOOLEAN(), nullable=False),
        sa.CheckConstraint("admin_count > 0", name="check_atleast_1_admin"),
        sa.CheckConstraint("length(description) > 8 OR description IS NULL"),
        sa.CheckConstraint("posts >= 0", name="check_posts_value"),
        sa.CheckConstraint("subscribers >= 0", name="check_subs_values"),
        sa.ForeignKeyConstraint(
            ["anime"],
            ["animes.id_"],
        ),
        sa.PrimaryKeyConstraint("id_"),
        sa.UniqueConstraint("name_", "anime", name="uq_name_anime"),
    )
    op.create_index(op.f("ix_forums_anime"), "forums", ["anime"], unique=False)
    op.create_table(
        "password_recovery_tokens",
        sa.Column("user_id", sa.BIGINT(), nullable=False),
        sa.Column(
            "expiry",
            postgresql.TIMESTAMP(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.Column("url_hash", postgresql.BYTEA(length=512), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id_"],
        ),
        sa.PrimaryKeyConstraint("user_id"),
        sa.UniqueConstraint("url_hash"),
    )
    op.create_index(
        op.f("ix_password_recovery_tokens_expiry"),
        "password_recovery_tokens",
        ["expiry"],
        unique=False,
    )
    op.create_table(
        "stream_links",
        sa.Column("anime_id", sa.INTEGER(), nullable=False),
        sa.Column("url", sa.VARCHAR(length=512), nullable=False),
        sa.Column("website", sa.VARCHAR(length=512), nullable=False),
        sa.ForeignKeyConstraint(["anime_id"], ["animes.id_"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("anime_id", "url"),
    )
    op.create_table(
        "user_tickets",
        sa.Column("id", sa.BIGINT(), nullable=False),
        sa.Column("user_id", sa.BIGINT(), nullable=False),
        sa.Column(
            "time_raised",
            postgresql.TIMESTAMP(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.Column("description", sa.VARCHAR(length=512), nullable=False),
        sa.CheckConstraint("length(description) >= 8"),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id_"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_user_tickets_user_id"), "user_tickets", ["user_id"], unique=False
    )
    op.create_table(
        "forum_admins",
        sa.Column("forum_id", sa.INTEGER(), nullable=False),
        sa.Column("user_id", sa.BIGINT(), nullable=False),
        sa.Column(
            "role",
            postgresql.ENUM("admin", "super", "owner", name="ADMIN_ROLES"),
            server_default=sa.text("'admin'"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["forum_id"], ["forums.id_"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id_"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("forum_id", "user_id"),
    )
    op.create_table(
        "forum_rules",
        sa.Column("forum_id", sa.INTEGER(), nullable=False),
        sa.Column("rule_number", sa.SMALLINT(), nullable=False),
        sa.Column("title", sa.VARCHAR(length=32), nullable=False),
        sa.Column(
            "body",
            sa.VARCHAR(length=128),
            server_default="No additional description provided for this rule.",
            nullable=False,
        ),
        sa.Column("author", sa.INTEGER(), nullable=False),
        sa.Column("time_created", postgresql.TIMESTAMP(), nullable=False),
        sa.CheckConstraint(
            "rule_number >= 1 AND rule_number <= 5", name="enforce_forum_rules_range"
        ),
        sa.ForeignKeyConstraint(
            ["author"],
            ["users.id_"],
        ),
        sa.ForeignKeyConstraint(["forum_id"], ["forums.id_"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("forum_id", "rule_number"),
        sa.UniqueConstraint("rule_number"),
    )
    op.create_table(
        "forum_subscriptions",
        sa.Column("user_id", sa.BIGINT(), nullable=False),
        sa.Column("forum_id", sa.INTEGER(), nullable=False),
        sa.Column(
            "time_subscribed",
            postgresql.TIMESTAMP(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["forum_id"], ["forums.id_"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id_"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("user_id", "forum_id"),
    )
    op.create_table(
        "posts",
        sa.Column("id_", sa.BIGINT(), autoincrement=True, nullable=False),
        sa.Column("author_id", sa.BIGINT(), nullable=False),
        sa.Column("forum_id", sa.INTEGER(), nullable=False),
        sa.Column("score", sa.INTEGER(), server_default=sa.text("0"), nullable=False),
        sa.Column(
            "total_comments", sa.INTEGER(), server_default=sa.text("0"), nullable=False
        ),
        sa.Column("title", sa.VARCHAR(length=16), nullable=False),
        sa.Column("body_text", sa.VARCHAR(length=32800), nullable=False),
        sa.Column("flair", sa.VARCHAR(length=16), nullable=True),
        sa.Column(
            "closed", sa.BOOLEAN(), server_default=sa.text("false"), nullable=False
        ),
        sa.Column(
            "time_posted",
            postgresql.TIMESTAMP(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.Column("saves", sa.INTEGER(), server_default=sa.text("0"), nullable=False),
        sa.Column("reports", sa.INTEGER(), server_default=sa.text("0"), nullable=False),
        sa.Column(
            "deleted", sa.BOOLEAN(), server_default=sa.text("false"), nullable=False
        ),
        sa.Column("time_deleted", postgresql.TIMESTAMP(), nullable=True),
        sa.Column("rtbf_hidden", sa.BOOLEAN(), nullable=True),
        sa.CheckConstraint(
            "length(body_text) <= 32800 OR body_text IS NULL", name="check_body_text"
        ),
        sa.CheckConstraint("length(title) >= 4", name="check_title_min_length"),
        sa.ForeignKeyConstraint(
            ["author_id"],
            ["users.id_"],
        ),
        sa.ForeignKeyConstraint(["forum_id"], ["forums.id_"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id_"),
    )
    op.create_index(op.f("ix_posts_author_id"), "posts", ["author_id"], unique=False)
    op.create_index(op.f("ix_posts_flair"), "posts", ["flair"], unique=False)
    op.create_index(op.f("ix_posts_title"), "posts", ["title"], unique=False)
    op.create_table(
        "comments",
        sa.Column("id_", sa.BIGINT(), autoincrement=True, nullable=False),
        sa.Column("author_id", sa.BIGINT(), nullable=False),
        sa.Column("parent_forum", sa.INTEGER(), nullable=False),
        sa.Column(
            "time_created",
            postgresql.TIMESTAMP(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.Column("body", sa.VARCHAR(length=8192), nullable=False),
        sa.Column("parent_post", sa.BIGINT(), nullable=False),
        sa.Column("score", sa.BIGINT(), server_default=sa.text("0"), nullable=False),
        sa.Column("reports", sa.INTEGER(), server_default=sa.text("0"), nullable=False),
        sa.Column(
            "deleted", sa.BOOLEAN(), server_default=sa.text("false"), nullable=False
        ),
        sa.Column("time_deleted", postgresql.TIMESTAMP(), nullable=True),
        sa.Column("rtbf_hidden", sa.BOOLEAN(), nullable=True),
        sa.CheckConstraint("reports > 0", name="check_reports_value"),
        sa.ForeignKeyConstraint(
            ["author_id"],
            ["users.id_"],
        ),
        sa.ForeignKeyConstraint(["parent_forum"], ["forums.id_"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["parent_post"], ["posts.id_"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id_"),
    )
    op.create_index(
        op.f("ix_comments_author_id"), "comments", ["author_id"], unique=False
    )
    op.create_index(
        op.f("ix_comments_parent_post"), "comments", ["parent_post"], unique=False
    )
    op.create_table(
        "post_reports",
        sa.Column("user_id", sa.BIGINT(), nullable=False),
        sa.Column("post_id", sa.BIGINT(), nullable=False),
        sa.Column(
            "report_tag",
            postgresql.ENUM(
                "spam", "harassment", "hate", "violence", "other", name="REPORT_TAGS"
            ),
            nullable=False,
        ),
        sa.Column("report_time", postgresql.TIMESTAMP(), nullable=False),
        sa.Column("report_description", sa.VARCHAR(length=256), nullable=False),
        sa.CheckConstraint("length(report_description) <= 8"),
        sa.ForeignKeyConstraint(["post_id"], ["posts.id_"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id_"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("user_id", "post_id", "report_tag"),
    )
    op.create_table(
        "post_saves",
        sa.Column("user_id", sa.BIGINT(), nullable=False),
        sa.Column("post_id", sa.BIGINT(), nullable=False),
        sa.ForeignKeyConstraint(["post_id"], ["posts.id_"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id_"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("user_id", "post_id"),
    )
    op.create_table(
        "post_votes",
        sa.Column("voter_id", sa.BIGINT(), nullable=False),
        sa.Column("post_id", sa.BIGINT(), nullable=False),
        sa.Column("vote", sa.BOOLEAN(), nullable=False),
        sa.ForeignKeyConstraint(["post_id"], ["posts.id_"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["voter_id"],
            ["users.id_"],
        ),
        sa.PrimaryKeyConstraint("voter_id", "post_id"),
    )
    op.create_table(
        "comment_reports",
        sa.Column("user_id", sa.BIGINT(), nullable=False),
        sa.Column("comment_id", sa.BIGINT(), nullable=False),
        sa.Column(
            "report_tag",
            postgresql.ENUM(
                "spam", "harassment", "hate", "violence", "other", name="REPORT_TAGS"
            ),
            nullable=False,
        ),
        sa.Column("report_time", postgresql.TIMESTAMP(), nullable=False),
        sa.Column("report_description", sa.VARCHAR(length=256), nullable=False),
        sa.ForeignKeyConstraint(["comment_id"], ["comments.id_"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id_"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("user_id", "comment_id", "report_tag"),
    )
    op.create_table(
        "comment_votes",
        sa.Column("voter_id", sa.BIGINT(), nullable=False),
        sa.Column("comment_id", sa.BIGINT(), nullable=False),
        sa.Column("vote", sa.BOOLEAN(), nullable=False),
        sa.ForeignKeyConstraint(["comment_id"], ["comments.id_"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["voter_id"],
            ["users.id_"],
        ),
        sa.PrimaryKeyConstraint("voter_id", "comment_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("comment_votes")
    op.drop_table("comment_reports")
    op.drop_table("post_votes")
    op.drop_table("post_saves")
    op.drop_table("post_reports")
    op.drop_index(op.f("ix_comments_parent_post"), table_name="comments")
    op.drop_index(op.f("ix_comments_author_id"), table_name="comments")
    op.drop_table("comments")
    op.drop_index(op.f("ix_posts_title"), table_name="posts")
    op.drop_index(op.f("ix_posts_flair"), table_name="posts")
    op.drop_index(op.f("ix_posts_author_id"), table_name="posts")
    op.drop_table("posts")
    op.drop_table("forum_subscriptions")
    op.drop_table("forum_rules")
    op.drop_table("forum_admins")
    op.drop_index(op.f("ix_user_tickets_user_id"), table_name="user_tickets")
    op.drop_table("user_tickets")
    op.drop_table("stream_links")
    op.drop_index(
        op.f("ix_password_recovery_tokens_expiry"),
        table_name="password_recovery_tokens",
    )
    op.drop_table("password_recovery_tokens")
    op.drop_index(op.f("ix_forums_anime"), table_name="forums")
    op.drop_table("forums")
    op.drop_table("anime_subscriptions")
    op.drop_table("anime_genres")
    op.drop_table("users")
    op.drop_table("genres")
    op.drop_table("animes")
    # ### end Alembic commands ###
