"""empty message

Revision ID: a639269cddd3
Revises: cec56bf97d17
Create Date: 2026-07-03 12:35:17.807065

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "a639269cddd3"
down_revision: Union[str, Sequence[str], None] = "cec56bf97d17"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("animes", "rating")
    op.drop_column("animes", "mal_rating")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "animes",
        sa.Column("mal_rating", sa.INTEGER(), autoincrement=False, nullable=True),
    )
    op.add_column(
        "animes",
        sa.Column(
            "rating",
            sa.NUMERIC(precision=3, scale=2),
            autoincrement=False,
            nullable=False,
        ),
    )
    # ### end Alembic commands ###
