"""adds_event_columns

Revision ID: a9cdcdd416de
Revises: ac751c82a6e0
Create Date: 2026-06-20 12:49:52.170466

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "a9cdcdd416de"
down_revision: Union[str, Sequence[str], None] = "ac751c82a6e0"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "anime_subscriptions",
        sa.Column(
            "is_subscribed",
            sa.BOOLEAN(),
            server_default=sa.text("true"),
            nullable=False,
        ),
    )
    op.add_column(
        "anime_subscriptions", sa.Column("last_event_id", sa.BIGINT(), nullable=False)
    )
    op.add_column("comment_votes", sa.Column("vote_type", sa.BOOLEAN(), nullable=False))
    op.add_column(
        "comment_votes", sa.Column("last_event_id", sa.BIGINT(), nullable=False)
    )
    op.drop_column("comment_votes", "vote")
    op.add_column(
        "forum_subscriptions",
        sa.Column(
            "is_subscribed",
            sa.BOOLEAN(),
            server_default=sa.text("true"),
            nullable=False,
        ),
    )
    op.add_column(
        "forum_subscriptions", sa.Column("last_event_id", sa.BIGINT(), nullable=False)
    )
    op.add_column(
        "post_saves",
        sa.Column(
            "is_saved", sa.BOOLEAN(), server_default=sa.text("true"), nullable=False
        ),
    )
    op.add_column("post_saves", sa.Column("last_event_id", sa.BIGINT(), nullable=False))
    op.add_column("post_votes", sa.Column("vote_type", sa.BOOLEAN(), nullable=False))
    op.add_column("post_votes", sa.Column("last_event_id", sa.BIGINT(), nullable=False))
    op.drop_column("post_votes", "vote")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "post_votes",
        sa.Column("vote", sa.BOOLEAN(), autoincrement=False, nullable=False),
    )
    op.drop_column("post_votes", "last_event_id")
    op.drop_column("post_votes", "vote_type")
    op.drop_column("post_saves", "last_event_id")
    op.drop_column("post_saves", "is_saved")
    op.drop_column("forum_subscriptions", "last_event_id")
    op.drop_column("forum_subscriptions", "is_subscribed")
    op.add_column(
        "comment_votes",
        sa.Column("vote", sa.BOOLEAN(), autoincrement=False, nullable=False),
    )
    op.drop_column("comment_votes", "last_event_id")
    op.drop_column("comment_votes", "vote_type")
    op.drop_column("anime_subscriptions", "last_event_id")
    op.drop_column("anime_subscriptions", "is_subscribed")
    # ### end Alembic commands ###
