"""adds_counter_dlq

Revision ID: ac751c82a6e0
Revises: ee3c37f5d96c
Create Date: 2026-06-19 18:21:33.636682

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "ac751c82a6e0"
down_revision: Union[str, Sequence[str], None] = "ee3c37f5d96c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "counters_dlq",
        sa.Column("id_", sa.BIGINT(), autoincrement=True, nullable=False),
        sa.Column("affected_table", sa.VARCHAR(length=64), nullable=False),
        sa.Column("affected_column", sa.VARCHAR(length=64), nullable=False),
        sa.Column(
            "failure_time",
            postgresql.TIMESTAMP(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.PrimaryKeyConstraint("id_"),
    )
    op.create_index(
        op.f("ix_counters_dlq_affected_column"),
        "counters_dlq",
        ["affected_column"],
        unique=False,
    )
    op.create_index(
        op.f("ix_counters_dlq_affected_table"),
        "counters_dlq",
        ["affected_table"],
        unique=False,
    )
    op.create_index(
        op.f("ix_counters_dlq_failure_time"),
        "counters_dlq",
        ["failure_time"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_counters_dlq_failure_time"), table_name="counters_dlq")
    op.drop_index(op.f("ix_counters_dlq_affected_table"), table_name="counters_dlq")
    op.drop_index(op.f("ix_counters_dlq_affected_column"), table_name="counters_dlq")
    op.drop_table("counters_dlq")
    # ### end Alembic commands ###
