"""Adds deletion mixins

Revision ID: ba411046cc75
Revises: 19ed1d233cb9
Create Date: 2026-06-23 11:40:58.414326

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "ba411046cc75"
down_revision: Union[str, Sequence[str], None] = "19ed1d233cb9"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "comments", sa.Column("deletion_author_event", sa.BIGINT(), nullable=True)
    )
    op.add_column(
        "forums", sa.Column("deletion_author_event", sa.BIGINT(), nullable=True)
    )
    op.add_column(
        "posts", sa.Column("deletion_author_event", sa.BIGINT(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("posts", "deletion_author_event")
    op.drop_column("forums", "deletion_author_event")
    op.drop_column("comments", "deletion_author_event")
    # ### end Alembic commands ###
