"""Updates events tables

Revision ID: c5867477cf90
Revises: 76d4417ceeb6
Create Date: 2026-09-06 15:49:48.397230

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "c5867477cf90"
down_revision: Union[str, Sequence[str], None] = "76d4417ceeb6"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    # NOTE: Manually adding the enum because alembic fails to inline-create new enums for column additions (ALTER TABLE ADD COLUMN)
    event_name_enum = postgresql.ENUM(
        "POST_CREATE",
        "POST_SAVE",
        "POST_UNSAVE",
        "POST_REPORT",
        "POST_VOTE",
        "POST_UNVOTE",
        "POST_DELETE",
        "ANIME_SUB",
        "ANIME_UNSUB",
        "COMMENT_CREATE",
        "COMMENT_VOTE",
        "COMMENT_UNVOTE",
        "COMMENT_REPORT",
        "COMMENT_DELETE",
        "FORUM_SUB",
        "FORUM_UNSUB",
        "FORUM_DELETE",
        "USER_CLEANUP",
        "USER_TICKET",
        "MALFORMED",
        "ORPHANED_POST_DELETE",
        "ORPHANED_COMMENT_DELETE",
        "DOWNSTREAM_USER_POST_DECREMENT",
        "DOWNSTREAM_FORUM_POST_DECREMENT",
        "DOWNSTREAM_USER_COMMENT_DECREMENT",
        "DOWNSTREAM_POST_COMMENT_DECREMENT",
        "DLQ_COUNTER",
        "DLQ_SIDE_EFFECTS",
        "USER_DELETION_EMAIL",
        "USER_REGISTRATION_EMAIL",
        "USER_PASSWORD_RECOVERY_EMAIL",
        name="EVENT_NAME",
    )
    event_name_enum.create(op.get_bind(), checkfirst=True)
    ### End manual commands ###

    op.create_table(
        "cache_side_effects",
        sa.Column("cache_se_emitted", sa.BOOLEAN(), nullable=False),
        sa.Column(
            "cache_se_payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False
        ),
        sa.Column("event_id", sa.TEXT(), nullable=False),
        sa.ForeignKeyConstraint(
            ["event_id"],
            ["stream_events.event_id"],
        ),
        sa.PrimaryKeyConstraint("event_id"),
    )
    op.create_index(
        "non_emitted_events",
        "cache_side_effects",
        ["event_id"],
        unique=False,
        postgresql_where=sa.text("NOT cache_se_emitted"),
    )
    op.drop_index(op.f("ix_counters_dlq_affected_column"), table_name="counters_dlq")
    op.drop_index(op.f("ix_counters_dlq_affected_table"), table_name="counters_dlq")
    op.drop_index(op.f("ix_counters_dlq_failure_time"), table_name="counters_dlq")
    op.drop_table("counters_dlq")
    op.drop_index(op.f("ix_side_effects_dlq_event_id"), table_name="side_effects_dlq")
    op.drop_index(
        op.f("ix_side_effects_dlq_side_effect_type"), table_name="side_effects_dlq"
    )
    op.drop_table("side_effects_dlq")
    op.add_column(
        "dlq_events", sa.Column("event_name", event_name_enum, nullable=False)
    )
    op.create_index(
        op.f("ix_dlq_events_event_name"), "dlq_events", ["event_name"], unique=False
    )
    op.add_column(
        "stream_events", sa.Column("event_name", event_name_enum, nullable=False)
    )
    op.create_index(
        op.f("ix_stream_events_event_name"),
        "stream_events",
        ["event_name"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    # NOTE: Manually adding the enum because alembic fails to inline-create new enums for column additions (ALTER TABLE ADD COLUMN)
    event_name_enum = postgresql.ENUM(
        "POST_CREATE",
        "POST_SAVE",
        "POST_UNSAVE",
        "POST_REPORT",
        "POST_VOTE",
        "POST_UNVOTE",
        "POST_DELETE",
        "ANIME_SUB",
        "ANIME_UNSUB",
        "COMMENT_CREATE",
        "COMMENT_VOTE",
        "COMMENT_UNVOTE",
        "COMMENT_REPORT",
        "COMMENT_DELETE",
        "FORUM_SUB",
        "FORUM_UNSUB",
        "FORUM_DELETE",
        "USER_CLEANUP",
        "USER_TICKET",
        "MALFORMED",
        "ORPHANED_POST_DELETE",
        "ORPHANED_COMMENT_DELETE",
        "DOWNSTREAM_USER_POST_DECREMENT",
        "DOWNSTREAM_FORUM_POST_DECREMENT",
        "DOWNSTREAM_USER_COMMENT_DECREMENT",
        "DOWNSTREAM_POST_COMMENT_DECREMENT",
        "DLQ_COUNTER",
        "DLQ_SIDE_EFFECTS",
        "USER_DELETION_EMAIL",
        "USER_REGISTRATION_EMAIL",
        "USER_PASSWORD_RECOVERY_EMAIL",
        name="EVENT_NAME",
    )
    event_name_enum.drop(op.get_bind(), checkfirst=True)
    ### End manual commands ###

    op.drop_index(op.f("ix_stream_events_event_name"), table_name="stream_events")
    op.drop_column("stream_events", "event_name")
    op.drop_index(op.f("ix_dlq_events_event_name"), table_name="dlq_events")
    op.drop_column("dlq_events", "event_name")
    op.create_table(
        "side_effects_dlq",
        sa.Column("id_", sa.BIGINT(), autoincrement=True, nullable=False),
        sa.Column("event_id", sa.BIGINT(), autoincrement=False, nullable=False),
        sa.Column(
            "side_effect_type",
            postgresql.ENUM(
                "CACHE_INVALIDATION",
                "INTENT_INVALIDATION",
                "COUNTER_UPDATE",
                name="SIDE_EFFECTS_TYPES",
            ),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "payload",
            postgresql.JSONB(astext_type=sa.Text()),
            autoincrement=False,
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id_", name=op.f("side_effects_dlq_pkey")),
    )
    op.create_index(
        op.f("ix_side_effects_dlq_side_effect_type"),
        "side_effects_dlq",
        ["side_effect_type"],
        unique=False,
    )
    op.create_index(
        op.f("ix_side_effects_dlq_event_id"),
        "side_effects_dlq",
        ["event_id"],
        unique=False,
    )
    op.create_table(
        "counters_dlq",
        sa.Column("id_", sa.BIGINT(), autoincrement=True, nullable=False),
        sa.Column(
            "affected_table", sa.VARCHAR(length=64), autoincrement=False, nullable=False
        ),
        sa.Column(
            "affected_column",
            sa.VARCHAR(length=64),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "failure_time",
            postgresql.TIMESTAMP(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "payload",
            postgresql.JSONB(astext_type=sa.Text()),
            autoincrement=False,
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id_", name=op.f("counters_dlq_pkey")),
    )
    op.create_index(
        op.f("ix_counters_dlq_failure_time"),
        "counters_dlq",
        ["failure_time"],
        unique=False,
    )
    op.create_index(
        op.f("ix_counters_dlq_affected_table"),
        "counters_dlq",
        ["affected_table"],
        unique=False,
    )
    op.create_index(
        op.f("ix_counters_dlq_affected_column"),
        "counters_dlq",
        ["affected_column"],
        unique=False,
    )
    op.drop_index(
        "non_emitted_events",
        table_name="cache_side_effects",
        postgresql_where=sa.text("NOT cache_se_emitted"),
    )
    op.drop_table("cache_side_effects")
    # ### end Alembic commands ###
