"""makes_users_last_login_nullable

Revision ID: cec56bf97d17
Revises: 0a1370421a2b
Create Date: 2026-07-03 11:52:23.639823

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "cec56bf97d17"
down_revision: Union[str, Sequence[str], None] = "0a1370421a2b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "users", "last_login", existing_type=postgresql.TIMESTAMP(), nullable=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "users", "last_login", existing_type=postgresql.TIMESTAMP(), nullable=False
    )
    # ### end Alembic commands ###
