"""adds StreamEvent

Revision ID: ed06aa294747
Revises: 4bd0490dba29
Create Date: 2026-06-18 10:42:10.174077

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "ed06aa294747"
down_revision: Union[str, Sequence[str], None] = "4bd0490dba29"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "stream_events",
        sa.Column("event_id", sa.TEXT(), nullable=False),
        sa.Column(
            "acknowledgement_time",
            postgresql.TIMESTAMP(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("event_id"),
    )
    op.create_index(
        op.f("ix_stream_events_acknowledgement_time"),
        "stream_events",
        ["acknowledgement_time"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_stream_events_acknowledgement_time"), table_name="stream_events"
    )
    op.drop_table("stream_events")
    # ### end Alembic commands ###
