"""removes_ack_time_col

Revision ID: ee3c37f5d96c
Revises: 33fe0a168e0a
Create Date: 2026-06-19 16:27:50.262003

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "ee3c37f5d96c"
down_revision: Union[str, Sequence[str], None] = "33fe0a168e0a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_dlq_events_acknowledgement_time"), table_name="dlq_events")
    op.drop_column("dlq_events", "acknowledgement_time")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "dlq_events",
        sa.Column(
            "acknowledgement_time",
            postgresql.TIMESTAMP(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.create_index(
        op.f("ix_dlq_events_acknowledgement_time"),
        "dlq_events",
        ["acknowledgement_time"],
        unique=False,
    )
    # ### end Alembic commands ###
