"""adds timestamp default

Revision ID: f00622df4456
Revises: 1cd84d8de9e2
Create Date: 2026-09-26 23:03:39.995062

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "f00622df4456"
down_revision: Union[str, Sequence[str], None] = "1cd84d8de9e2"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("forums", "created_at", server_default=sa.text("CURRENT_TIMESTAMP"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("forums", "created_at", server_default=None)
    # ### end Alembic commands ###
