"""Abstracts side-effect columns to mixin class

Revision ID: f8e3eade649c
Revises: c5867477cf90
Create Date: 2026-09-07 18:26:59.106968

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "f8e3eade649c"
down_revision: Union[str, Sequence[str], None] = "c5867477cf90"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "cache_side_effects",
        sa.Column("side_effects_emitted", sa.BOOLEAN(), nullable=False),
    )
    op.add_column(
        "cache_side_effects",
        sa.Column(
            "side_effects_payload",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=False,
        ),
    )
    op.drop_column("cache_side_effects", "cache_se_emitted")
    op.drop_column("cache_side_effects", "cache_se_payload")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "cache_side_effects",
        sa.Column(
            "cache_se_payload",
            postgresql.JSONB(astext_type=sa.Text()),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.add_column(
        "cache_side_effects",
        sa.Column(
            "cache_se_emitted", sa.BOOLEAN(), autoincrement=False, nullable=False
        ),
    )
    op.drop_column("cache_side_effects", "side_effects_payload")
    op.drop_column("cache_side_effects", "side_effects_emitted")
    # ### end Alembic commands ###
