[database]
POSTGRES_HOST="resource_server_database"
POSTGRES_PORT=5432
POSTGRES_DATABASE="resource_db"


[database.SQLALCHEMY]
SQLALCHEMY_POOL_SIZE=16
SQLALCHEMY_MAX_OVERFLOW=8
SQLALCHEMY_POOL_RECYCLE=600
SQLALCHEMY_POOL_TIMEOUT=15
SQLALCHEMY_TRACK_MODIFICATIONS=false

[redis]
[redis.app]
HOST="resource_server_redis"
PORT=6379
DB=0


[redis.internal]
HOST="resource_server_redis"
PORT=6379
DB=1

[cache]
# All units in seconds, unless specified otherwise
TTL_CAP=86400
TTL_PROMOTION=15
TTL_STRONGEST=1200
TTL_STRONG=600
TTL_WEAK=300
TTL_EPHEMERAL=60

NF_SENTINEL_KEY="__NF__"
NF_SENTINEL_VALUE="1"

[worker]
MAX_RETRIES=2

DLQ_NAME="DLQ"
COUNTER_REGISTRY_NAME="counters"
COUNTER_RETRY_REGISTRY_NAME="counters:retries"
COUNTER_REGISTRY_REFRESH_INTERVAL=1800          # seconds
COUNTER_FLUSH_LOCK_TTL=120                      # seconds
COUNTER_FLUSH_INTERVAL=10                       # seconds

CONSUMER_READ_INTERVAL=500                      # milliseconds
CONSUMER_READ_SIZE=1000
CONSUMER_BLOCK_TIME=500                         # milliseconds
CONSUMER_GROUP_NAME="consumers"

IQ_CONSUMER_BASE_WAITING_TIME=2                     # seconds
IQ_CONSUMER_BATCH_SIZE_QUOTA=0.1
IQ_CONSUMER_GET_TIMEOUT=0.1                         # seconds
IQ_CONSUMER_SLEEP_INTERVAL=0.01                     # seconds

DOWNSTREAM_COUNTER_BATCH_SIZE=10000

RECLAIM_THRESHOLD=120_000                           # milliseconds
RECLAIMATION_CHECK_INTERVAL=30_000                  # milliseconds
MAX_DELIVERIES=3
