[READERS]
[READERS.STREAMS]
POSTS = 1
COMMENTS = 1
FORUMS = 1
ANIMES = 1
USERS = 1
DOWNSTREAM_DELETIONS = 1
DOWNSTREAM_COUNTER_DECREMENTS = 1
DLQ = 1

[WORKERS]
[WORKERS.STREAMS]
[WORKERS.STREAMS.POSTS]
POST_CREATE = 1
POST_DELETE = 1
POST_VOTE = 1
POST_SAVE = 1
POST_REPORT = 1

[WORKERS.STREAMS.COMMENTS]
COMMENT_CREATE = 1
COMMENT_DELETE = 1
COMMENT_VOTE = 1
COMMENT_REPORT = 1

[WORKERS.STREAMS.FORUMS]
FORUM_DELETE = 1
FORUM_SUBSCRIBE = 1

[WORKERS.STREAMS.ANIMES]
ANIME_SUBSCRIBE = 1

[WORKERS.STREAMS.DOWNSTREAM_DELETION]
USER_CLEANUP = 1
ORPHANED_POST_DELETE = 1
ORPHANED_COMMENT_DELETE = 1

[WORKERS.STREAMS.DOWNSTREAM_DECREMENT]
DOWNSTREAM_USER_POST_DECREMENT = 1
DOWNSTREAM_USER_COMMENT_DECREMENT = 1
DOWNSTREAM_FORUM_POST_DECREMENT = 1
DOWNSTREAM_POST_COMMENT_DECREMENT = 1

[WORKERS.STREAMS.DLQ]
DLQ = 1

[WORKERS.COUNTERS]
WORKERS = 1
RETRY_WORKERS = 1
