[USER]
USER_CLEANUP = 1

[POSTS]
POST_CREATE = 1
POST_SAVE = 1
POST_UNSAVE = 1
POST_REPORT = 1
POST_VOTE = 1
POST_UNVOTE = 1
POST_DELETE = 1

[COMMENTS]
COMMENT_CREATE = 1
COMMENT_VOTE = 1
COMMENT_UNVOTE = 1
COMMENT_REPORT = 1
COMMENT_DELETE = 1

[ANIMES]
ANIME_SUB = 1
ANIME_UNSUB = 1

[FORUMS]
FORUM_SUB = 1
FORUM_UNSUB = 1

[COUNTERS]
COUNTERS = 1

[ORPHANED]
ORPHANED_POST_DELETE = 1
ORPHANED_COMMENT_DELETE = 1

[DOWNSTREAM]
DOWNSTREAM_POST_DECREMENT = 1
DOWNSTREAM_COMMENT_DECREMENT = 1
