[core]
APPLICAITON_ROOT="/api/v1"
PORT=8080

[jwks]
JWKS_FILENAME="jwks.json"
PUBLIC_PEM_BASE_DIRECTORY="public_keys"
PRIVATE_PEM_BASE_DIRECTORY="private_keys"
JWKS_CAP=3

[redis]
[[redis.synced_store]]
HOST="auth_server_synced_store"
PORT=6379
DB=0
DECODE_RESPONSES=false

[[redis.token_store]]
HOST="auth_server_token_store"
PORT=6379
DB=0
DECODE_RESPONSES=false

[database]
POSTGRES_HOST="auth_server_database"
POSTGRES_PORT=5432
POSTGRES_DATABASE="auth_db"

[database.sqlalchemy]
SQLALCHEMY_POOL_SIZE=20
SQLALCHEMY_MAX_OVERFLOW=10
SQLALCHEMY_POOL_RECYCLE=600
SQLALCHEMY_POOL_TIMEOUT=15
SQLALCHEMY_TRACK_MODIFICATIONS=0

[keys]
MAX_VALID_KEYS=3
KEY_ROTATION_COOLDOWN=86400

[admin]
SUSPICIOUS_LOOKBACK_TIME=1
MAX_ACTIVITY_LIMIT=5
ADMIN_SESSION_DURATION=900
MAX_SESSION_ITERATIONS=5
