\getenv AUTH_SERVER_POSTGRES_USERNAME AUTH_SERVER_POSTGRES_USERNAME
\getenv AUTH_SERVER_POSTGRES_PASSWORD AUTH_SERVER_POSTGRES_PASSWORD
\getenv AUTH_DB_NAME AUTH_DB_NAME

CREATE DATABASE :"AUTH_DB_NAME";

\c :"AUTH_DB_NAME"

CREATE USER :"AUTH_SERVER_POSTGRES_USERNAME"
WITH PASSWORD :"AUTH_SERVER_POSTGRES_PASSWORD";

GRANT CONNECT ON DATABASE :"AUTH_DB_NAME"
TO :'AUTH_SERVER_POSTGRES_USERNAME';

ALTER DEFAULT PRIVILEGES IN SCHEMA public
GRANT SELECT ON TABLES TO :"AUTH_SERVER_POSTGRES_USERNAME";

GRANT SELECT ON ALL TABLES IN SCHEMA public
TO :"AUTH_SERVER_POSTGRES_USERNAME";

GRANT INSERT ON keydata, admins, suspicious_activities
TO :"AUTH_SERVER_POSTGRES_USERNAME";

GRANT UPDATE (time_deleted, last_login) ON admins TO :"AUTH_SERVER_POSTGRES_USERNAME";
GRANT UPDATE (expired_at, rotated_out_at, rotated_by, manual_rotation) ON keydata TO :"AUTH_SERVER_POSTGRES_USERNAME";
