#!/bin/bash
set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
    CREATE USER "$AUTH_SERVER_POSTGRES_USERNAME" 
    WITH PASSWORD '$AUTH_SERVER_POSTGRES_PASSWORD';

    GRANT CONNECT ON DATABASE "$POSTGRES_DB" TO "$AUTH_SERVER_POSTGRES_USERNAME";
    GRANT USAGE ON SCHEMA public TO "$AUTH_SERVER_POSTGRES_USERNAME";

    -- This says: "Whatever the 'postgres' user creates later, let AUTH_SERVER use it"
    ALTER DEFAULT PRIVILEGES FOR ROLE "$POSTGRES_USER" IN SCHEMA public 
    GRANT SELECT, INSERT, UPDATE ON TABLES TO "$AUTH_SERVER_POSTGRES_USERNAME";

    ALTER DEFAULT PRIVILEGES FOR ROLE "$POSTGRES_USER" IN SCHEMA public 
    GRANT USAGE, SELECT, UPDATE ON SEQUENCES TO "$AUTH_SERVER_POSTGRES_USERNAME";
EOSQL