CREATE DATABASE :"POSTGRES_DATABASE";

\c :"POSTGRES_DATABASE"

-- Resource server user
CREATE USER :"AUTH_WORKER_POSTGRES_USERNAME"
WITH PASSWORD :"AUTH_WORKER_POSTGRES_PASSWORD";

GRANT CONNECT ON DATABASE :"POSTGRES_DATABASE"
TO :"AUTH_WORKER_POSTGRES_USERNAME";

ALTER DEFAULT PRIVILEGES IN SCHEMA public
GRANT SELECT ON TABLES TO :"AUTH_WORKER_POSTGRES_USERNAME";

GRANT SELECT ON ALL TABLES IN SCHEMA public
TO :"AUTH_WORKER_POSTGRES_USERNAME";

GRANT INSERT ON keydata, admins, suspicious_activities
TO :"AUTH_WORKER_POSTGRES_USERNAME";

GRANT UPDATE (time_deleted, last_login) ON admins TO :"AUTH_WORKER_POSTGRES_USERNAME";
GRANT UPDATE (expired_at, rotated_out_at, rotated_by, manual_rotation) ON keydata TO :"AUTH_WORKER_POSTGRES_USERNAME";
