"""removes_admin_key_columns

Revision ID: 5a3464348577
Revises: d52c79981f32
Create Date: 2026-09-20 12:42:15.051021

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "5a3464348577"
down_revision: Union[str, Sequence[str], None] = "d52c79981f32"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("admins", "signing_key")
    op.drop_column("admins", "verification_key")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "admins",
        sa.Column(
            "verification_key", postgresql.BYTEA(), autoincrement=False, nullable=False
        ),
    )
    op.add_column(
        "admins",
        sa.Column(
            "signing_key", postgresql.BYTEA(), autoincrement=False, nullable=False
        ),
    )
    # ### end Alembic commands ###
