"""init

Revision ID: 649f4acaf78c
Revises:
Create Date: 2026-05-27 19:33:01.910114

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "649f4acaf78c"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "admins",
        sa.Column("id_", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("username", sa.VARCHAR(length=64), nullable=False),
        sa.Column(
            "role",
            postgresql.ENUM("staff", "super", name="admin_roles"),
            nullable=False,
        ),
        sa.Column("password_hash", postgresql.BYTEA(), nullable=False),
        sa.Column("password_salt", postgresql.BYTEA(), nullable=False),
        sa.Column(
            "time_deleted",
            sa.TIMESTAMP(),
            server_default=sa.text("null"),
            nullable=True,
        ),
        sa.Column(
            "last_login",
            sa.TIMESTAMP(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.Column(
            "locked", sa.BOOLEAN(), server_default=sa.text("false"), nullable=False
        ),
        sa.Column("created_by", sa.INTEGER(), nullable=False),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["admins.id_"],
        ),
        sa.PrimaryKeyConstraint("id_"),
        sa.UniqueConstraint("username"),
    )
    op.create_table(
        "keydata",
        sa.Column("kid", sa.VARCHAR(length=16), nullable=False),
        sa.Column(
            "alg",
            sa.VARCHAR(length=8),
            server_default=sa.text("'ES256'"),
            nullable=False,
        ),
        sa.Column("curve", sa.VARCHAR(length=16), nullable=False),
        sa.Column(
            "epoch",
            sa.TIMESTAMP(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.Column(
            "rotated_out_at",
            sa.TIMESTAMP(),
            server_default=sa.text("null"),
            nullable=False,
        ),
        sa.Column(
            "expired_at", sa.TIMESTAMP(), server_default=sa.text("null"), nullable=False
        ),
        sa.Column("private_pem", postgresql.BYTEA(), nullable=False),
        sa.Column("public_pem", postgresql.BYTEA(), nullable=False),
        sa.Column(
            "manual_rotation",
            sa.BOOLEAN(),
            server_default=sa.text("false"),
            nullable=False,
        ),
        sa.Column("rotated_by", sa.INTEGER(), nullable=False),
        sa.ForeignKeyConstraint(
            ["rotated_by"],
            ["admins.id_"],
        ),
        sa.PrimaryKeyConstraint("kid"),
        sa.UniqueConstraint("epoch"),
        sa.UniqueConstraint("private_pem"),
        sa.UniqueConstraint("public_pem"),
    )
    op.create_index(
        op.f("ix_keydata_rotated_by"), "keydata", ["rotated_by"], unique=False
    )
    op.create_table(
        "suspicious_activities",
        sa.Column("id_", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("suspect", sa.INTEGER(), nullable=False),
        sa.Column(
            "time_logged",
            sa.TIMESTAMP(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.Column("description", sa.VARCHAR(length=64), nullable=False),
        sa.ForeignKeyConstraint(
            ["suspect"],
            ["admins.id_"],
        ),
        sa.PrimaryKeyConstraint("id_"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("suspicious_activities")
    op.drop_index(op.f("ix_keydata_rotated_by"), table_name="keydata")
    op.drop_table("keydata")
    op.drop_table("admins")
    # ### end Alembic commands ###
