"""empty message

Revision ID: 792513ee857c
Revises: c3f9b8d5e5f5
Create Date: 2026-06-14 17:41:22.176452

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "792513ee857c"
down_revision: Union[str, Sequence[str], None] = "c3f9b8d5e5f5"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("admins", "password_salt")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "admins",
        sa.Column(
            "password_salt", postgresql.BYTEA(), autoincrement=False, nullable=False
        ),
    )
    # ### end Alembic commands ###
