"""adds_permissions_enum

Revision ID: 8ede8d8bdb6a
Revises: 649f4acaf78c
Create Date: 2026-05-30 11:07:57.853153

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "8ede8d8bdb6a"
down_revision: Union[str, Sequence[str], None] = "649f4acaf78c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###
