"""empty message

Revision ID: 936866dd9020
Revises: 792513ee857c
Create Date: 2026-07-03 14:29:07.071062

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "936866dd9020"
down_revision: Union[str, Sequence[str], None] = "792513ee857c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "keydata", "rotated_out_at", existing_type=postgresql.TIMESTAMP(), nullable=True
    )
    op.alter_column(
        "keydata", "expired_at", existing_type=postgresql.TIMESTAMP(), nullable=True
    )
    op.alter_column(
        "keydata",
        "manual_rotation",
        existing_type=sa.BOOLEAN(),
        nullable=True,
        existing_server_default=sa.text("false"),
    )
    op.alter_column("keydata", "rotated_by", existing_type=sa.INTEGER(), nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("keydata", "rotated_by", existing_type=sa.INTEGER(), nullable=False)
    op.alter_column(
        "keydata",
        "manual_rotation",
        existing_type=sa.BOOLEAN(),
        nullable=False,
        existing_server_default=sa.text("false"),
    )
    op.alter_column(
        "keydata", "expired_at", existing_type=postgresql.TIMESTAMP(), nullable=False
    )
    op.alter_column(
        "keydata",
        "rotated_out_at",
        existing_type=postgresql.TIMESTAMP(),
        nullable=False,
    )
    # ### end Alembic commands ###
