"""updates enums

Revision ID: a4de8e78b37b
Revises: 5a3464348577
Create Date: 2026-09-22 18:06:30.313016

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "a4de8e78b37b"
down_revision: Union[str, Sequence[str], None] = "5a3464348577"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


_CURRENT_ADMIN_ROLES = ("super", "staff")
_PREVIOUS_ADMIN_ROLES = ("staff", "super")
_ADMIN_PERMISSIONS = (
    "read_key",
    "rotate_key",
    "invalidate_key",
    "clean_keystore",
    "delete_admin",
    "lock_admin",
    "unlock_admin",
    "create_admin",
)


def _enum_labels_sql(labels: Sequence[str]) -> str:
    return ", ".join(f"'{label}'" for label in labels)


def _recreate_admin_roles(labels: Sequence[str]) -> None:
    # PostgreSQL enum types cannot be dropped while a column depends on them.
    op.alter_column(
        "admins",
        "role",
        type_=sa.Text(),
        existing_nullable=False,
        postgresql_using="role::text",
    )
    op.execute("DROP TYPE IF EXISTS admin_roles")
    op.execute(f"CREATE TYPE admin_roles AS ENUM ({_enum_labels_sql(labels)})")
    op.alter_column(
        "admins",
        "role",
        type_=postgresql.ENUM(
            *labels,
            name="admin_roles",
            create_type=False,
        ),
        existing_nullable=False,
        postgresql_using="role::text::admin_roles",
    )


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "admins",
        "username",
        existing_type=sa.VARCHAR(length=64),
        type_=sa.VARCHAR(length=32),
        existing_nullable=False,
    )
    op.create_check_constraint(
        "ck_username_min_length",
        "admins",
        "length(username) >= 4",
    )

    _recreate_admin_roles(_CURRENT_ADMIN_ROLES)
    op.execute("DROP TYPE IF EXISTS admin_permissions")
    op.execute(
        f"CREATE TYPE admin_permissions AS ENUM "
        f"({_enum_labels_sql(_ADMIN_PERMISSIONS)})"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DROP TYPE IF EXISTS admin_permissions")
    _recreate_admin_roles(_PREVIOUS_ADMIN_ROLES)

    op.drop_constraint(
        "ck_username_min_length",
        "admins",
        type_="check",
    )
    op.alter_column(
        "admins",
        "username",
        existing_type=sa.VARCHAR(length=32),
        type_=sa.VARCHAR(length=64),
        existing_nullable=False,
    )
    # ### end Alembic commands ###
