"""empty message

Revision ID: c3f9b8d5e5f5
Revises: 8ede8d8bdb6a
Create Date: 2026-06-01 12:54:51.500794

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "c3f9b8d5e5f5"
down_revision: Union[str, Sequence[str], None] = "8ede8d8bdb6a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "admins", sa.Column("signing_key", postgresql.BYTEA(), nullable=False)
    )
    op.add_column(
        "admins", sa.Column("verification_key", postgresql.BYTEA(), nullable=False)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("admins", "verification_key")
    op.drop_column("admins", "signing_key")
    # ### end Alembic commands ###
