from enum import StrEnum


class ProcessorName(StrEnum):
    INSERTIONS = "INSERTIONS"
    DELETIONS = "DELETIONS"
    DOWNSTREAM_DELETIONS = "DOWNSTREAM_DELETIONS"
    DOWNSTREAM_COUNTER_DECREMENTS = "DOWNSTREAM_COUNTER_DECREMENTS"
    DLQ = "DLQ"
    COUNTERS = "COUNTERS"
    DLQ_COUNTERS = "DLQ_COUNTERS"
    PENDING_RECYCLER = "PENDING_RECYCLER"
